In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
f_d=pd.read_excel('/Users/abhijeetkashyap/Desktop/project version 1/Copy of flats.xlsx')

In [4]:
f_d.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
1321,4 BHK Flat in Sector 54 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,DLF The Belaire3.9 ★,7 Crore,"₹ 23,333/sq.ft.",Super Built up area 3000(278.71 sq.m.),4 Bedrooms,6 Bathrooms,3+ Balconies,"Servant Room,Pooja Room,Store Room","1259, Sector 54 Gurgaon, Gurgaon, Haryana",12nd of 30 Floors,East,5 to 10 Year Old,"['Sector 42-43 Metro station', 'Horizon 1 Mall...","Situated in sector 54 gurgaon, dlf the belaire...","['6 Wardrobe', '7 Fan', '1 Exhaust Fan', '10 L...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4.5 out of 5', 'Construction5 out ...",W68384702
975,4 BHK Flat in Sector 99A Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Pareena Coban Residences,1.38 Crore,"₹ 7,150/sq.ft.",Super Built up area 2352(218.51 sq.m.)Built Up...,4 Bedrooms,5 Bathrooms,3+ Balconies,"Servant Room,Others","Sector 99A Gurgaon, Gurgaon, Haryana",1st of 20 Floors,South-East,1 to 5 Year Old,"['Gopal Super Market', 'Little Need Super Mark...",This lovely 4 bhk apartment/flat in sector 99a...,"['6 AC', '1 Modular Kitchen', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle3 out of 5...",B69102822
2449,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,HCBS Sports Ville3.6 ★,35 Lac,₹ 4/sq.ft.,Built Up area: 737147 (68483.2 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sohna, Gurgaon, Haryana",8th of 13 Floors,NaN,1 to 5 Year Old,"['The roadside cafe', 'GD Goenka Mess', 'ROyal...","View is awesome, towards the aravalli and fres...","['1 Water Purifier', '1 Fridge', '1 Fan', '1 G...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area4 out of 5', 'Construction4 out of...",Y69214772
2502,2 BHK Flat in Gwal Pahari,https://www.99acres.com/2-bhk-bedroom-apartmen...,Suncity Vatsal Valley,1.38 Crore,"₹ 12,212/sq.ft.",Built Up area: 1130 (104.98 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Gwal Pahari, Gurgaon, Haryana",4th of 4 Floors,East,Under Construction,"['Sector 55-56 Metro Station', 'Banjara Market...",This property is available with complete roof ...,"['2 Wardrobe', '2 Geyser', '10 Light', '3 AC',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN,Z69094060
153,3 BHK Flat in Garauli Kalan,https://www.99acres.com/3-bhk-bedroom-apartmen...,ashiyara 2,45 Lac,"₹ 4,500/sq.ft.",Super Built up area 1000(92.9 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Garauli Kalan, Gurgaon, Haryana",18th of 19 Floors,NaN,2025-01-01 00:00:00,"['Shri Balaji Hospital and Trauma Center', 'Ka...",Residential apartment for sell.The property ha...,NaN,NaN,NaN,Y68479394

In [5]:
f_d.shape

(3028, 20)

In [6]:
f_d.columns

Index(['property_name', 'link', 'society', 'price', 'area', 'areaWithType',
       'bedRoom', 'bathroom', 'balcony', 'additionalRoom', 'address',
       'floorNum', 'facing', 'agePossession', 'nearbyLocations', 'description',
       'furnishDetails', 'features', 'rating', 'property_id'],
      dtype='object')

In [7]:
f_d.isnull().sum()

property_name         0
link                  0
society               1
price                20
area                 13
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1333
address              25
floorNum             21
facing              900
agePossession        20
nearbyLocations     114
description          19
furnishDetails      824
features            433
rating              351
property_id          19
dtype: int64

## cleaning of flat dataset

In [8]:
f_dc=f_d.copy()
f_dc.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
1369,4 BHK Flat in Sector 65 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Emaar MGF Emerald Floors Premier3.8 ★,2.77 Crore,"₹ 14,025/sq.ft.",Carpet area: 1975 (183.48 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Study Room,Servant Room","Sector 65 Gurgaon, Gurgaon, Haryana",3rd of 5 Floors,North-East,1 to 5 Year Old,"['WorldMark Gurgaon', 'Sohna Road', 'Golf Cour...","A 3,4bedroom resale flat, located in sector-65...","['1 Water Purifier', '1 Fridge', '1 Fan', '1 E...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction5 out ...",N69869760
424,3 BHK Flat in Sector 108 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Sobha City,3.35 Crore,"₹ 13,266/sq.ft.",Super Built up area 2072.9(192.58 sq.m.),3 Bedrooms,4 Bathrooms,2 Balconies,NaN,"Sector 108 Gurgaon, Gurgaon, Haryana",19th of 24 Floors,NaN,0 to 1 Year Old,"['Dwarka Sector 21', 'Dwarka Expressway', 'Vas...",Sobha city gurgaon by sobha ltd.\nOver 86% of ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4.5 out of...",Z67172840
589,4 BHK Flat in Sector 83 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Vatika Gurgaon 213.7 ★,1.25 Crore,"₹ 7,812/sq.ft.",Super Built up area 2390(222.04 sq.m.)Carpet a...,4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Block A, Sector 83 Gurgaon, Gurgaon, Haryana",12nd of 14 Floors,South-West,5 to 10 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...","The unit is a row flat, it has 4 bathrooms and...","['4 Fan', '5 Light', '3 Wardrobe', 'No AC', 'N...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4.5 out ...",C61573480
1283,2 BHK Flat in Sector 70A Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,AIPL Club Residences,85 Lac,"₹ 9,139/sq.ft.",Super Built up area 930(86.4 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 70A Gurgaon, Gurgaon, Haryana",5th of 9 Floors,South-East,1 to 5 Year Old,"['Airia Mall', 'Golf Corse Ext. Rd', 'National...",Check out this 2 bhk apartment for sale in aip...,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Environment5 out of 5', 'Lifestyle4 out of 5...",J69964070
1842,2 BHK Flat in Sector 104 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Godrej Summit3.7 ★,75 Lac,"₹ 5,910/sq.ft.",Super Built up area 1269(117.89 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Others,"Godrej Summit, Sector-104 Gurgaon, Sector 104 ...",6th of 17 Floors,East,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",A 2 bhk flat is available for sale in gurgaon ...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4 out ...",U50040234

In [9]:
f_dc[f_dc['society'].isnull()]

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
2767,2 BHK Flat in Sector 78 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,NaN,60 Lac,"₹ 3,692/sq.ft.",Built Up area: 1625 (150.97 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",T8073153

In [10]:
f_dc[f_dc['property_name']=='2 BHK Flat in Sector 78 Gurgaon']['society'].value_counts()

society
Umang Monsoon Breeze    5
Raheja Revanta          1
Name: count, dtype: int64

In [11]:
# drop row
f_dc.drop(index=2767,axis=0,inplace=True)

In [12]:
f_dc['society'].isnull().sum()

0

In [13]:
f_dc['society']

0                                  maa bhagwati residency
1                                            Apna Enclave
2                                  Tulsiani Easy in Homes
3                                     Smart World Orchard
4                                        Parkwood Westend
5                          Signature Global Infinity Mall
6                                              The Cocoon
7                                        ATS Triumph3.9 ★
8                                       Vatika Xpressions
9                                          Raheja Revanta
10                               Signature Global City 81
11                                 HCBS Sports Ville3.6 ★
12                                     Supertech Araville
13                                                 Godrej
14                              Shree Vardhman Flora3.8 ★
15                                             Sobha City
16                                           Senate Court
17              Shapoorji Pallonji Joyville Gurugram4.0 ★
18                      Signature Global Orchard Avenue 2
19                             Central Park Flower Valley
20                                       Smart World Gems
21                                         Bestech Altura
22                                       Smart World Gems
23                            Emaar Imperial Gardens3.8 ★
24                                La Vida by Tata Housing
25                              The New People Apartments
26                                            The Serenas
27                                    M3M Golfestate4.4 ★
28               Central Park Resort Belgravia Residences
29                                          Apex builders
30                                         Godrej Habitat
31                                    Ompee K S Residency
32                                            Bhawna CGHS
33                                    Adani Aangan Arcade
34                                        Sare Green Parc
35                              Shree Vardhman Flora3.8 ★
36                                         Supertech Hues
37                                 Chintels Paradiso3.9 ★
38                                 Breez Global Hill View
39                                        ILD Greens4.1 ★
40                                   Ansal Sushant Lok CI
41                                       Ashiana Mulberry
42                                        Godrej Meridien
43                                 Mapsko Casa Bella3.8 ★
44                                        Pooja Apartment
45                             Signature Global Park4.0 ★
46                            DLF New Town Heights 13.9 ★
47                                             Paras Dews
48                                             Godrej Air
49                                    DLF The Primus3.9 ★
50                  Emaar MGF Emerald Floors Premier3.8 ★
51                                DLF Regency Park 13.6 ★
52                                     Supertech Araville
53                             Signature Global Park4.0 ★
54                               Maxworth City Residences
55                                           Deepak Minda
56                                  Shree Shyam residency
57                                         Pivotal Devaan
58                            Unitech The Residences3.7 ★
59                                     CHD Avenue 713.6 ★
60                         Gokuldham Society, Bahadurgarh
61                                 Silverglades The Melia
62                Sare Crescent Parc Royal Greens Phase 1
63                                Umang Winter Hills3.9 ★
64                                        Ramprastha Skyz
65                                       4S Aradhya Homes
66                                        ILD Greens4.1 ★
67                            BPTP Freedom Park Life4.0 ★
68                                         Godrej Habitat
69                                   Ramsons Kshitij3.7 ★
70                                      Sidhartha NCR One
71                                         Raheja Sampada
72                                  Signature The Serenas
73                          Pareena Laxmi Apartments3.6 ★
74                               Satya The Hermitage3.5 ★
75                                       Smart World Gems
76                                 GLS Arawali Homes3.8 ★
77                             Signature Global Park4.0 ★
78                          Bestech Park View City 23.9 ★
79                              Shree Vardhman Flora3.8 ★
80                               AFNHB Jalvayu Vihar3.7 ★
81                                          M3M Soulitude
82                                          Pyramid Elite
83                                Emaar MGF Palm Terraces
84                                        Anamika Enclave
85                                 HCBS Sports Ville3.6 ★
86                                     Puri The Aravallis
87                            Brisk Lumbini Terrace Homes
88                          HUDA Ashok Vihar Phase 13.9 ★
89                                                My Home
90                                  Signature Global City
91                                            M3M Heights
92                             Signature Global Park4.0 ★
93                             Signature Global Park4.0 ★
94                                     Godrej Nature Plus
95                                         Supertech Hues
96                            DLF New Town Heights 13.9 ★
97           Central Park Flower Valley Aqua Front Towers
98                                     Ambience Creacions
99                              Signature Global City 63A
100                                     Godrej Oasis3.9 ★
101                                           M3M Skycity
102                                    Supertech Araville
103                                   Smart World Orchard
104                                HCBS Sports Ville3.6 ★
105                                    Emaar Palm Premier
106                                    Godrej Nature Plus
107                                      Godrej Aria3.8 ★
108                                  Ramsons Kshitij3.7 ★
109                                         Conscient One
110                         Pareena Laxmi Apartments3.6 ★
111                                         Pyramid Elite
112                                        Raheja Revanta
113                                           M3M Skycity
114                            Signature The Roselia3.6 ★
115                                        Not Applicable
116                                    Godrej Nature Plus
117                                       Ramprastha City
118                                       Smartworld 1DXP
119                           Ansal Housing Highland Park
120                                 Czar Mahira Homes 63A
121                             Breez Global Heights4.2 ★
122                                   Trisara Our Homes 3
123                                         M3M Soulitude
124                             Emaar MGF Palm Hills4.0 ★
125                                       Ramprastha City
126                              Pareena Coban Residences
127                               La Vida by Tata Housing
128                               La Vida by Tata Housing
129                           Godrej Summit Premia Towers
130                                       Ardee City3.8 ★
131                                 M3M One Key Resiments
132                                      Ansal Heights 86
133                                       MVN Athens3.7 ★
134                                 Signature The Serenas
135                          Sushant Lok 1 Builder Floors
136                                  Umang Monsoon Breeze
137                                         GLS Avenue 51
138                          Signature Global Solera3.7 ★
139                                    Supertech Araville
140                                           Greenopolis
141          Central Park Flower Valley Aqua Front Towers
142                                            Sare Homes
143             Vatika Sovereign Next Sector-82 A Gurgaon
144                                        Bhagwati sadan
145                                      Smart World Gems
146                                         micasa sec 68
147                                  Eldeco Accolade3.8 ★
148                                            Hero Homes
149                                           Shyam Sadan
150                                           M3M Heights
151                                   hanumanta apartment
152                                    Supertech Hilltown
153                                            ashiyara 2
154                                  Raheja Vedaanta3.6 ★
155                                       BPTP Terra3.8 ★
156                                      Green Court3.7 ★
157                                M3M Golf Hills Phase 1
158                         Abhinav Group Housing Society
159                                 Pyramid Urban Homes 2
160                                           M3M Heights
161                                    Godrej Nature Plus
162                                   Smart World Orchard
163                                    Ashiana Anmol3.5 ★
164                                  Signature Signum 95A
165                               Umang Winter Hills3.9 ★
166                                        Aardhya homesh
167                                            ROF Ananda
168                                      Smart World Gems
169                                        Assotech Blith
170                                           Essel Tower
171                                          Raheja Vanya
172                                    Vatika INXT Floors
173                                   Palam Vihar Society
174                                     Godrej Oasis3.9 ★
175                             DLF New Town Heights3.7 ★
176                             DLF New Town Heights3.7 ★
177         sonata group housing society sector 1 Manesar
178                                        Supertech Hues
179                                Krrish Florence Estate
180                         Piedmont Taksila heights3.6 ★
181                                    Experion Heartsong
182                                      SS The Leaf3.8 ★
183                                            M3M Urbana
184                                   AIPL Zen Residences
185                                DLF Regal Gardens3.9 ★
186                                            Godrej Air
187                                 Suncity Vatsal Valley
188                                 Shree shyam residency
189                                Project Krishna Colony
190                                       MVN Athens3.7 ★
191                                     M3M Antalya Hills
192                            Central Park Flower Valley
193                                           M3M Capital
194                                    Ansal Heights3.2 ★
195                                          Malibu Towne
196                                   AIPL Zen Residences
197                                           M3M Heights
198                                HCBS Sports Ville3.6 ★
199                                HCBS Sports Ville3.6 ★
200                                            JMD Empire
201                             Housing Apna Enclave3.7 ★
202                                        Assotech Blith
203                                       Pareena Mi Casa
204                                  Suncity Heights3.7 ★
205                                       Lotus Homz4.0 ★
206                        Ramson kshitij Sec-95 Gurugram
207                                   Maruti Vihar Colony
208                                           M3M Heights
209                                      Supertech Basera
210                        Signature Global the Millennia
211                                         M3M Soulitude
212                                          Raheja Vanya
213            Ganpati apartment  2, Laxman Vihar Phase 1
214                            Ramprastha The Atrium3.4 ★
215                                        M3M Golfestate
216                                  Eldeco Accolade3.8 ★
217                                           M3M Heights
218                                           M3M Heights
219                                 Vatika Sovereign Next
220                                           M3M Heights
221                                           M3M Heights
222                                           M3M Heights
223                                   South City 1 Floors
224                                          Allure Homes
225                                           Zara Aavaas
226                        Sidhartha NCR One Phase 14.2 ★
227                                    CHD Avenue 713.6 ★
228                       Ramprastha The Edge Towers3.5 ★
229                                    Supertech Araville
230                                     Imperia Aashiyara
231                               La Vida by Tata Housing
232             Shapoorji Pallonji Joyville Gurugram4.0 ★
233                                   Smart World Orchard
234                                    Supertech Araville
235                                   Smart World Orchard
236                           Unitech The Residences3.7 ★
237                           Emaar Imperial Gardens3.8 ★
238                                            Sare Homes
239                                           Greenopolis
240                                        Pivotal Devaan
241                                       Today Callidora
242                M M Residency, Krishna Colony, Gurgaon
243                               Signature Global Park 4
244                                    CHD Avenue 713.6 ★
245                                  Park Royal Apartment
246               Vatika Boulevard Residences and Heights
247                        Signature Global the Millennia
248                                           M3M Heights
249             Shapoorji Pallonji Joyville Gurugram4.0 ★
250                                        Tulip Monsella
251                         Shyamkunj ashok vihar pahse 2
252                                    Godrej Nature Plus
253                                           M3M Heights
254                                   M3M The Marina4.0 ★
255                                       Emaar Digihomes
256                                  Umang Monsoon Breeze
257                                  Mapsko Paradise3.9 ★
258                                        Cancon Enclave
259                                    Tata Primanti4.1 ★
260                                     MRG World Ultimus
261                            sonata group housing Gh 24
262                                         BPTP Pedestal
263                                   Smart World Orchard
264                                  HSIIDC Sidco Aravali
265                                      Godrej Aria3.8 ★
266                                        Assotech Blith
267                               Sare Crescent Parc3.5 ★
268                                        Unitech Vistas
269                                    Supertech Araville
270                           Ansal Housing Highland Park
271                                      Tulip White3.5 ★
272                                Mapsko Casa Bella3.8 ★
273                       Unitech Uniworld Gardens 23.4 ★
274                                             ILD Grand
275                                           M3M Capital
276                                        Unitech Vistas
277                       Ramprastha The Edge Towers3.5 ★
278                                      Smart World Gems
279                                 Sapphire Eighty Three
280                              Pareena Coban Residences
281                               Sare Crescent Parc3.5 ★
282                                         DLF The Grove
283                                     Baani City Center
284                                     Indiabulls Enigma
285                                      SS The Leaf3.8 ★
286                                               society
287                                   Smart World One DXP
288                                  Sukhshanti Apartment
289                                   M3M Golfestate4.4 ★
290                      Bestech Park View Residency3.9 ★
291                                            SS Almeria
292                                      JMD Gardens4.4 ★
293                                  CGHS Agrim Apartment
294                                      Global Hill View
295                              Ireo Victory Valley4.1 ★
296                                       Emaar Digihomes
297                                    Godrej Nature Plus
298                               DLF Carlton Estate4.0 ★
299                                   Smart World Orchard
300                            Signature Global Park4.0 ★
301                          Railway Officers RPF Society
302                                            Godrej Air
303                             Emaar MGF Palm Hills4.0 ★
304                                          Maruti Vihar
305                                    Vasant Appartments
306                                      Ansal Heights 86
307             Shapoorji Pallonji Joyville Gurugram4.0 ★
308                                    Puri The Aravallis
309                                  The Close North4.0 ★
310                                   Smart World Orchard
311                             Emaar Gurgaon Greens4.1 ★
312                                    Godrej Nature Plus
313                                Landmark The Residency
314                                           M3M Capital
315                           Emaar Imperial Gardens3.8 ★
316                             DLF Belvedere Towers3.8 ★
317                                             m3m crown
318                                       Godrej 1014.0 ★
319                             Central Park Resorts4.4 ★
320                                  Sukhshanti Apartment
321                                   M3M Golfestate4.4 ★
322                      Bestech Park View Residency3.9 ★
323                                            SS Almeria
324                              Ireo Victory Valley4.1 ★
325                                       Emaar Digihomes
326                               DLF Carlton Estate4.0 ★
327                            Signature Global Park4.0 ★
328                          Railway Officers RPF Society
329                                            Godrej Air
330                             Emaar MGF Palm Hills4.0 ★
331                                          Maruti Vihar
332                                    Vasant Appartments
333                                      Ansal Heights 86
334             Shapoorji Pallonji Joyville Gurugram4.0 ★
335                                  The Close North4.0 ★
336                             Emaar Gurgaon Greens4.1 ★
337                                Landmark The Residency
338                           Emaar Imperial Gardens3.8 ★
339                             DLF Belvedere Towers3.8 ★
340                                       Godrej 1014.0 ★
341                                        Tulip Monsella
342               Sare Crescent Parc Royal Greens Phase 1
343                                  AIPL Club Residences

In [14]:
f_dc.isnull().sum()

property_name         0
link                  0
society               0
price                20
area                 13
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1332
address              25
floorNum             20
facing              899
agePossession        20
nearbyLocations     113
description          19
furnishDetails      824
features            432
rating              351
property_id          19
dtype: int64

In [15]:
import re
f_dc['society'] = f_dc['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [16]:
f_dc['society']

0                              maa bhagwati residency
1                                        apna enclave
2                              tulsiani easy in homes
3                                 smart world orchard
4                                    parkwood westend
5                      signature global infinity mall
6                                          the cocoon
7                                         ats triumph
8                                   vatika xpressions
9                                      raheja revanta
10                           signature global city 81
11                                  hcbs sports ville
12                                 supertech araville
13                                             godrej
14                               shree vardhman flora
15                                         sobha city
16                                       senate court
17               shapoorji pallonji joyville gurugram
18                  signature global orchard avenue 2
19                         central park flower valley
20                                   smart world gems
21                                     bestech altura
22                                   smart world gems
23                             emaar imperial gardens
24                            la vida by tata housing
25                          the new people apartments
26                                        the serenas
27                                     m3m golfestate
28           central park resort belgravia residences
29                                      apex builders
30                                     godrej habitat
31                                ompee k s residency
32                                        bhawna cghs
33                                adani aangan arcade
34                                    sare green parc
35                               shree vardhman flora
36                                     supertech hues
37                                  chintels paradiso
38                             breez global hill view
39                                         ild greens
40                               ansal sushant lok ci
41                                   ashiana mulberry
42                                    godrej meridien
43                                  mapsko casa bella
44                                    pooja apartment
45                              signature global park
46                               dlf new town heights
47                                         paras dews
48                                         godrej air
49                                     dlf the primus
50                   emaar mgf emerald floors premier
51                                   dlf regency park
52                                 supertech araville
53                              signature global park
54                           maxworth city residences
55                                       deepak minda
56                              shree shyam residency
57                                     pivotal devaan
58                             unitech the residences
59                                         chd avenue
60                     gokuldham society, bahadurgarh
61                             silverglades the melia
62            sare crescent parc royal greens phase 1
63                                 umang winter hills
64                                    ramprastha skyz
65                                   4s aradhya homes
66                                         ild greens
67                             bptp freedom park life
68                                     godrej habitat
69                                    ramsons kshitij
70                                  sidhartha ncr one
71                                     raheja sampada
72                              signature the serenas
73                           pareena laxmi apartments
74                                satya the hermitage
75                                   smart world gems
76                                  gls arawali homes
77                              signature global park
78                             bestech park view city
79                               shree vardhman flora
80                                afnhb jalvayu vihar
81                                      m3m soulitude
82                                      pyramid elite
83                            emaar mgf palm terraces
84                                    anamika enclave
85                                  hcbs sports ville
86                                 puri the aravallis
87                        brisk lumbini terrace homes
88                             huda ashok vihar phase
89                                            my home
90                              signature global city
91                                        m3m heights
92                              signature global park
93                              signature global park
94                                 godrej nature plus
95                                     supertech hues
96                               dlf new town heights
97       central park flower valley aqua front towers
98                                 ambience creacions
99                          signature global city 63a
100                                      godrej oasis
101                                       m3m skycity
102                                supertech araville
103                               smart world orchard
104                                 hcbs sports ville
105                                emaar palm premier
106                                godrej nature plus
107                                       godrej aria
108                                   ramsons kshitij
109                                     conscient one
110                          pareena laxmi apartments
111                                     pyramid elite
112                                    raheja revanta
113                                       m3m skycity
114                             signature the roselia
115                                    not applicable
116                                godrej nature plus
117                                   ramprastha city
118                                   smartworld 1dxp
119                       ansal housing highland park
120                             czar mahira homes 63a
121                              breez global heights
122                               trisara our homes 3
123                                     m3m soulitude
124                              emaar mgf palm hills
125                                   ramprastha city
126                          pareena coban residences
127                           la vida by tata housing
128                           la vida by tata housing
129                       godrej summit premia towers
130                                        ardee city
131                             m3m one key resiments
132                                  ansal heights 86
133                                        mvn athens
134                             signature the serenas
135                      sushant lok 1 builder floors
136                              umang monsoon breeze
137                                     gls avenue 51
138                           signature global solera
139                                supertech araville
140                                       greenopolis
141      central park flower valley aqua front towers
142                                        sare homes
143         vatika sovereign next sector-82 a gurgaon
144                                    bhagwati sadan
145                                  smart world gems
146                                     micasa sec 68
147                                   eldeco accolade
148                                        hero homes
149                                       shyam sadan
150                                       m3m heights
151                               hanumanta apartment
152                                supertech hilltown
153                                        ashiyara 2
154                                   raheja vedaanta
155                                        bptp terra
156                                       green court
157                            m3m golf hills phase 1
158                     abhinav group housing society
159                             pyramid urban homes 2
160                                       m3m heights
161                                godrej nature plus
162                               smart world orchard
163                                     ashiana anmol
164                              signature signum 95a
165                                umang winter hills
166                                    aardhya homesh
167                                        rof ananda
168                                  smart world gems
169                                    assotech blith
170                                       essel tower
171                                      raheja vanya
172                                vatika inxt floors
173                               palam vihar society
174                                      godrej oasis
175                              dlf new town heights
176                              dlf new town heights
177     sonata group housing society sector 1 manesar
178                                    supertech hues
179                            krrish florence estate
180                          piedmont taksila heights
181                                experion heartsong
182                                       ss the leaf
183                                        m3m urbana
184                               aipl zen residences
185                                 dlf regal gardens
186                                        godrej air
187                             suncity vatsal valley
188                             shree shyam residency
189                            project krishna colony
190                                        mvn athens
191                                 m3m antalya hills
192                        central park flower valley
193                                       m3m capital
194                                     ansal heights
195                                      malibu towne
196                               aipl zen residences
197                                       m3m heights
198                                 hcbs sports ville
199                                 hcbs sports ville
200                                        jmd empire
201                              housing apna enclave
202                                    assotech blith
203                                   pareena mi casa
204                                   suncity heights
205                                        lotus homz
206                    ramson kshitij sec-95 gurugram
207                               maruti vihar colony
208                                       m3m heights
209                                  supertech basera
210                    signature global the millennia
211                                     m3m soulitude
212                                      raheja vanya
213        ganpati apartment  2, laxman vihar phase 1
214                             ramprastha the atrium
215                                    m3m golfestate
216                                   eldeco accolade
217                                       m3m heights
218                                       m3m heights
219                             vatika sovereign next
220                                       m3m heights
221                                       m3m heights
222                                       m3m heights
223                               south city 1 floors
224                                      allure homes
225                                       zara aavaas
226                           sidhartha ncr one phase
227                                        chd avenue
228                        ramprastha the edge towers
229                                supertech araville
230                                 imperia aashiyara
231                           la vida by tata housing
232              shapoorji pallonji joyville gurugram
233                               smart world orchard
234                                supertech araville
235                               smart world orchard
236                            unitech the residences
237                            emaar imperial gardens
238                                        sare homes
239                                       greenopolis
240                                    pivotal devaan
241                                   today callidora
242            m m residency, krishna colony, gurgaon
243                           signature global park 4
244                                        chd avenue
245                              park royal apartment
246           vatika boulevard residences and heights
247                    signature global the millennia
248                                       m3m heights
249              shapoorji pallonji joyville gurugram
250                                    tulip monsella
251                     shyamkunj ashok vihar pahse 2
252                                godrej nature plus
253                                       m3m heights
254                                    m3m the marina
255                                   emaar digihomes
256                              umang monsoon breeze
257                                   mapsko paradise
258                                    cancon enclave
259                                     tata primanti
260                                 mrg world ultimus
261                        sonata group housing gh 24
262                                     bptp pedestal
263                               smart world orchard
264                              hsiidc sidco aravali
265                                       godrej aria
266                                    assotech blith
267                                sare crescent parc
268                                    unitech vistas
269                                supertech araville
270                       ansal housing highland park
271                                       tulip white
272                                 mapsko casa bella
273                          unitech uniworld gardens
274                                         ild grand
275                                       m3m capital
276                                    unitech vistas
277                        ramprastha the edge towers
278                                  smart world gems
279                             sapphire eighty three
280                          pareena coban residences
281                                sare crescent parc
282                                     dlf the grove
283                                 baani city center
284                                 indiabulls enigma
285                                       ss the leaf
286                                           society
287                               smart world one dxp
288                              sukhshanti apartment
289                                    m3m golfestate
290                       bestech park view residency
291                                        ss almeria
292                                       jmd gardens
293                              cghs agrim apartment
294                                  global hill view
295                               ireo victory valley
296                                   emaar digihomes
297                                godrej nature plus
298                                dlf carlton estate
299                               smart world orchard
300                             signature global park
301                      railway officers rpf society
302                                        godrej air
303                              emaar mgf palm hills
304                                      maruti vihar
305                                vasant appartments
306                                  ansal heights 86
307              shapoorji pallonji joyville gurugram
308                                puri the aravallis
309                                   the close north
310                               smart world orchard
311                              emaar gurgaon greens
312                                godrej nature plus
313                            landmark the residency
314                                       m3m capital
315                            emaar imperial gardens
316                              dlf belvedere towers
317                                         m3m crown
318                                            godrej
319                              central park resorts
320                              sukhshanti apartment
321                                    m3m golfestate
322                       bestech park view residency
323                                        ss almeria
324                               ireo victory valley
325                                   emaar digihomes
326                                dlf carlton estate
327                             signature global park
328                      railway officers rpf society
329                                        godrej air
330                              emaar mgf palm hills
331                                      maruti vihar
332                                vasant appartments
333                                  ansal heights 86
334              shapoorji pallonji joyville gurugram
335                                   the close north
336                              emaar gurgaon greens
337                            landmark the residency
338                            emaar imperial gardens
339                              dlf belvedere towers
340                                            godrej
341                                    tulip monsella
342           sare crescent parc royal greens phase 1
343                              aipl club residences
344                            experion the heartsong
345                             signature global city
346                            bestech park view city
347                                emaar palm gardens
348                                        chd avenue
349                                        mvn athens
350                                 mahindra luminare
351                                   raheja navodaya
352                                godrej nature plus
353                                        m3m urbana
354                            experion the heartsong
355                                        sobha city
356                                godrej nature plus
357                               smart world orchard
358                          emaar mgf the palm drive
359                       bestech park view residency
360                       bestech park view residency
361                                        m3m merlin
362                                  dlf the skycourt
363                              emaar gurgaon greens
364                               afnhb jalvayu vihar
365                                  dlf regency park
366                               ireo victory valley
367                                ambience creacions
368                          signature global city 92
369      the khushboo cooperative housing society ltd

In [17]:
# price column
f_dc[f_dc['price'].isnull()]['society'].value_counts()

society
signature global orchard avenue 2        1
signature global solera                  1
godrej oasis                             1
umang monsoon breeze                     1
corona optus                             1
supertech araville                       1
uphar lakshya homes                      1
ss residency                             1
ild greens                               1
jammu and kashmir bank employees cghs    1
chanderlok society                       1
assotech blith                           1
maple heights                            1
greenopolis                              1
ikon tower baani city centre             1
pareena coban residences                 1
breez global hill view                   1
my home                                  1
tulip monsella                           1
godrej aria , sector 79 , gurgaon        1
Name: count, dtype: int64

In [18]:
f_dc.dtypes

property_name      object
link               object
society            object
price              object
area               object
areaWithType       object
bedRoom            object
bathroom           object
balcony            object
additionalRoom     object
address            object
floorNum           object
facing             object
agePossession      object
nearbyLocations    object
description        object
furnishDetails     object
features           object
rating             object
property_id        object
dtype: object

In [19]:
f_dc.shape

(3027, 20)

In [20]:
# area column
# Rename the 'OldName' column to 'NewName' in place
f_dc.rename(columns={'area': 'area_persqft'}, inplace=True)

In [21]:
f_dc['area_persqft']=f_dc['area_persqft'].str.replace('₹','').str.strip().str.slice(stop=-7)

In [22]:
f_dc['bedRoom']=f_dc['bedRoom'].str.slice(stop=-8).str.strip()

In [23]:
f_dc['bathroom']=f_dc['bathroom'].str.slice(stop=-9).str.strip()

In [24]:
f_dc['balcony']=f_dc['balcony'].apply(lambda a:str(a).split(' ')[0] if isinstance(a,str) else a)

In [25]:
f_dc['additionalRoom']=f_dc['additionalRoom'].fillna('not avilable')

In [26]:
f_dc['additionalRoom'].isnull().sum()

0

In [27]:
f_dc

                                        property_name  \
0                        2 BHK Flat in Krishna Colony
1                           2 BHK Flat in Ashok Vihar
2                                 2 BHK Flat in Sohna
3                     2 BHK Flat in Sector 61 Gurgaon
4                     2 BHK Flat in Sector 92 Gurgaon
5                     2 BHK Flat in Sector 36 Gurgaon
6             3 BHK Flat in Dwarka Expressway Gurgaon
7                    3 BHK Flat in Sector 104 Gurgaon
8                    2 BHK Flat in Sector 88B Gurgaon
9                     3 BHK Flat in Sector 78 Gurgaon
10                    2 BHK Flat in Sector 81 Gurgaon
11                                2 BHK Flat in Sohna
12                    3 BHK Flat in Sector 79 Gurgaon
13                    2 BHK Flat in Sector 33 Gurgaon
14                    2 BHK Flat in Sector 90 Gurgaon
15                   4 BHK Flat in Sector 108 Gurgaon
16                    1 BHK Flat in Sector 62 Gurgaon
17                   2 BHK Flat in Sector 102 Gurgaon
18                    2 BHK Flat in Sector 93 Gurgaon
19                      3 BHK Flat in Sector-33 Sohna
20                    2 BHK Flat in Sector 89 Gurgaon
21                    3 BHK Flat in Sector 79 Gurgaon
22                    2 BHK Flat in Sector 89 Gurgaon
23                   3 BHK Flat in Sector 102 Gurgaon
24                   3 BHK Flat in Sector 113 Gurgaon
25                     5 BHK Flat in Sector 1 Gurgaon
26                    2 BHK Flat in Sector 36 Gurgaon
27                    3 BHK Flat in Sector 65 Gurgaon
28                    3 BHK Flat in Sector 48 Gurgaon
29                   2 BHK Flat in Sector 37C Gurgaon
30                     2 BHK Flat in Sector 3 Gurgaon
31                      2 BHK Flat in New Palam Vihar
32                    4 BHK Flat in Sector 43 Gurgaon
33                   2 BHK Flat in Sector 88A Gurgaon
34                    3 BHK Flat in Sector 92 Gurgaon
35                    2 BHK Flat in Sector 90 Gurgaon
36                    2 BHK Flat in Sector 68 Gurgaon
37                   3 BHK Flat in Sector 109 Gurgaon
38                                2 BHK Flat in Sohna
39                   2 BHK Flat in Sector 37C Gurgaon
40                    3 BHK Flat in Sector 43 Gurgaon
41                                2 BHK Flat in Sohna
42                   3 BHK Flat in Sector 106 Gurgaon
43                    4 BHK Flat in Sector 82 Gurgaon
44        2 BHK Flat in Ashok Vihar Phase 3 Extension
45                                3 BHK Flat in Sohna
46                    4 BHK Flat in Sector 90 Gurgaon
47                   2 BHK Flat in Sector 106 Gurgaon
48                    3 BHK Flat in Sector 85 Gurgaon
49                   3 BHK Flat in Sector 82A Gurgaon
50                    3 BHK Flat in Sector 65 Gurgaon
51                          2 BHK Flat in DLF Phase 4
52                    2 BHK Flat in Sector 79 Gurgaon
53                                3 BHK Flat in Sohna
54                   2 BHK Flat in Sector 10A Gurgaon
55                4 BHK Flat in Sector 1A IMT Manesar
56                  1 BHK Flat in Block A Surya Vihar
57                    1 BHK Flat in Sector 84 Gurgaon
58                    3 BHK Flat in Sector 33 Gurgaon
59                    2 BHK Flat in Sector 71 Gurgaon
60               2 BHK Flat in Sector-7 Housing Board
61                                2 BHK Flat in Sohna
62                    4 BHK Flat in Sector 92 Gurgaon
63                    2 BHK Flat in Sector 77 Gurgaon
64                   3 BHK Flat in Sector 37D Gurgaon
65                   4 BHK Flat in Sector 67A Gurgaon
66                   3 BHK Flat in Sector 37C Gurgaon
67                    3 BHK Flat in Sector 57 Gurgaon
68                     2 BHK Flat in Sector 3 Gurgaon
69                    2 BHK Flat in Sector 95 Gurgaon
70                    2 BHK Flat in Sector 95 Gurgaon
71                    3 BHK Flat in Sector 92 Gurgaon
72                                2 BHK Flat in Sohna
73                   2 BHK Flat in Sector 99A Gurgaon
74                   2 BHK Flat in Sector 103 Gurgaon
75                    3 BHK Flat in Sector 89 Gurgaon
76                                2 BHK Flat in Sohna
77                                2 BHK Flat in Sohna
78                    3 BHK Flat in Sector 49 Gurgaon
79                    3 BHK Flat in Sector 90 Gurgaon
80                    3 BHK Flat in Sector 30 Gurgaon
81                    3 BHK Flat in Sector 89 Gurgaon
82                    2 BHK Flat in Sector 86 Gurgaon
83                    5 BHK Flat in Sector 66 Gurgaon
84                     2 BHK Flat in Sector 15 Part 1
85                                2 BHK Flat in Sohna
86                    3 BHK Flat in Sector 61 Gurgaon
87                   3 BHK Flat in Sector 109 Gurgaon
88                         2 BHK Flat in Laxman Vihar
89                      2 BHK Flat in New Palam Vihar
90                   2 BHK Flat in Sector 37D Gurgaon
91                    2 BHK Flat in Sector 65 Gurgaon
92                                3 BHK Flat in Sohna
93                                3 BHK Flat in Sohna
94                      3 BHK Flat in Sector-33 Sohna
95                    2 BHK Flat in Sector 68 Gurgaon
96                    4 BHK Flat in Sector 90 Gurgaon
97                      3 BHK Flat in Sector-33 Sohna
98                    2 BHK Flat in Sector 22 Gurgaon
99                   3 BHK Flat in Sector 63A Gurgaon
100                  3 BHK Flat in Sector 88A Gurgaon
101                   3 BHK Flat in Sector 65 Gurgaon
102                   3 BHK Flat in Sector 79 Gurgaon
103                   2 BHK Flat in Sector 61 Gurgaon
104                               1 BHK Flat in Sohna
105                   3 BHK Flat in Sector 77 Gurgaon
106                     3 BHK Flat in Sector-33 Sohna
107                   2 BHK Flat in Sector 79 Gurgaon
108                   2 BHK Flat in Sector 95 Gurgaon
109                  1 BHK Flat in Sector 109 Gurgaon
110                  2 BHK Flat in Sector 99A Gurgaon
111                   2 BHK Flat in Sector 86 Gurgaon
112                   1 BHK Flat in Sector 78 Gurgaon
113                   2 BHK Flat in Sector 65 Gurgaon
114                  2 BHK Flat in Sector 95A Gurgaon
115                        2 BHK Flat in Laxman Vihar
116                     3 BHK Flat in Sector-33 Sohna
117           3 BHK Flat in Dwarka Expressway Gurgaon
118                  4 BHK Flat in Sector 113 Gurgaon
119                  3 BHK Flat in Sector 103 Gurgaon
120                  3 BHK Flat in Sector 63A Gurgaon
121                               2 BHK Flat in Sohna
122                               2 BHK Flat in Sohna
123                   3 BHK Flat in Sector 89 Gurgaon
124                   3 BHK Flat in Sector 77 Gurgaon
125           3 BHK Flat in Dwarka Expressway Gurgaon
126                  3 BHK Flat in Sector 99A Gurgaon
127                  2 BHK Flat in Sector 113 Gurgaon
128                  2 BHK Flat in Sector 113 Gurgaon
129                  2 BHK Flat in Sector 104 Gurgaon
130                   4 BHK Flat in Sector 52 Gurgaon
131                   1 BHK Flat in Sector 67 Gurgaon
132                   3 BHK Flat in Sector 86 Gurgaon
133                               2 BHK Flat in Sohna
134                               2 BHK Flat in Sohna
135                 3 BHK Flat in Sushant Lok Phase 1
136                   3 BHK Flat in Sector 78 Gurgaon
137                   2 BHK Flat in Sector 92 Gurgaon
138                  2 BHK Flat in Sector 107 Gurgaon
139                   2 BHK Flat in Sector 79 Gurgaon
140                   3 BHK Flat in Sector 89 Gurgaon
141                     3 BHK Flat in Sector-33 Sohna
142                   4 BHK Flat in Sector 92 Gurgaon
143                  4 BHK Flat in Sector 82A Gurgaon
144                  3 BHK Flat in Sector 12A Gurgaon
145                   3 BHK Flat in Sector 89 Gurgaon
146                          2 BHK Flat in Sohna Road
147                               3 BHK Flat in Sohna
148                  3 BHK Flat in Sector 104 Gurgaon
149                 2 BHK Flat in Ashok Vihar Phase 2
150                   3 BHK Flat in Sector 65 Gurgaon
151                        2 BHK Flat in Rajiv Colony
152                    3 BHK Flat in Sector 2 Gurgaon
153                       3 BHK Flat in Garauli Kalan
154                  2 BHK Flat in Sector 108 Gurgaon
155                  4 BHK Flat in Sector 37D Gurgaon
156                   2 BHK Flat in Sector 90 Gurgaon
157                   3 BHK Flat in Sector 79 Gurgaon
158                     3 BHK Flat in Bhawani Enclave
159                   2 BHK Flat in Sector 86 Gurgaon
160                   3 BHK Flat in Sector 65 Gurgaon
161                     3 BHK Flat in Sector-33 Sohna
162                   3 BHK Flat in Sector 61 Gurgaon
163                               2 BHK Flat in Sohna
164                  2 BHK Flat in Sector 95A Gurgaon
165                   3 BHK Flat in Sector 77 Gurgaon
166                  4 BHK Flat in Sector 67A Gurgaon
167                   1 BHK Flat in Sector 95 Gurgaon
168                   2 BHK Flat in Sector 89 Gurgaon
169                   2 BHK Flat in Sector 99 Gurgaon
170                         3 BHK Flat in IFFCO Chowk
171                  2 BHK Flat in Sector 99A Gurgaon
172                  2 BHK Flat in Sector 82A Gurgaon
173                         4 BHK Flat in Palam Vihar
174                  3 BHK Flat in Sector 88A Gurgaon
175                   4 BHK Flat in Sector 91 Gurgaon
176                   4 BHK Flat in Sector 91 Gurgaon
177                4 BHK Flat in near sector 1 market
178                   2 BHK Flat in Sector 68 Gurgaon
179                   3 BHK Flat in Sector 70 Gurgaon
180                  3 BHK Flat in Sector 37C Gurgaon
181           3 BHK Flat in Dwarka Expressway Gurgaon
182                   3 BHK Flat in Sector 85 Gurgaon
183                   1 BHK Flat in Sector 67 Gurgaon
184                  2 BHK Flat in Sector 70A Gurgaon
185                   4 BHK Flat in Sector 90 Gurgaon
186                   3 BHK Flat in Sector 85 Gurgaon
187                         3 BHK Flat in Gwal Pahari
188                 1 BHK Flat in Block A Surya Vihar
189                    2 BHK Flat in Sector 7 Gurgaon
190                               2 BHK Flat in Sohna
191                   3 BHK Flat in Sector 79 Gurgaon
192                          3 BHK Flat in Sohna Road
193                  4 BHK Flat in Sector 113 Gurgaon
194                   2 BHK Flat in Sector 92 Gurgaon
195                         3 BHK Flat in Malibu Town
196                  2 BHK Flat in Sector 70A Gurgaon
197                   2 BHK Flat in Sector 65 Gurgaon
198                               2 BHK Flat in Sohna
199                               2 BHK Flat in Sohna
200                    2 BHK Flat in Golf Course Road
201                    2 BHK Flat in Sector 4 Gurgaon
202                   3 BHK Flat in Sector 99 Gurgaon
203                   4 BHK Flat in Sector 68 Gurgaon
204                   3 BHK Flat in Sector 54 Gurgaon
205                  2 BHK Flat in Sector 111 Gurgaon
206                   2 BHK Flat in Sector 95 Gurgaon
207                          2 BHK Flat in Chakkarpur
208                   2 BHK Flat in Sector 65 Gurgaon
209                   2 BHK Flat in Sector 79 Gurgaon
210                  2 BHK Flat in Sector 37D Gurgaon
211                   3 BHK Flat in Sector 89 Gurgaon
212                  2 BHK Flat in Sector 99A Gurgaon
213                        2 BHK Flat in Laxman Vihar
214                  3 BHK Flat in Sector 37D Gurgaon
215                   2 BHK Flat in Sector 79 Gurgaon
216                               2 BHK Flat in Sohna
217                   3 BHK Flat in Sector 65 Gurgaon
218                   3 BHK Flat in Sector 65 Gurgaon
219                  5 BHK Flat in Sector 82A Gurgaon
220                   3 BHK Flat in Sector 65 Gurgaon
221                   2 BHK Flat in Sector 65 Gurgaon
222                   3 BHK Flat in Sector 65 Gurgaon
223                   4 BHK Flat in Sector 41 Gurgaon
224                   2 BHK Flat in Sector 12 Gurgaon
225                  2 BHK Flat in Sector 104 Gurgaon
226                   2 BHK Flat in Sector 95 Gurgaon
227                   3 BHK Flat in Sector 71 Gurgaon
228                  2 BHK Flat in Sector 37D Gurgaon
229                   2 BHK Flat in Sector 79 Gurgaon
230                  2 BHK Flat in Sector 37C Gurgaon
231                  3 BHK Flat in Sector 113 Gurgaon
232                  2 BHK Flat in Sector 102 Gurgaon
233                   2 BHK Flat in Sector 61 Gurgaon
234                   3 BHK Flat in Sector 79 Gurgaon
235                   3 BHK Flat in Sector 61 Gurgaon
236                   2 BHK Flat in Sector 33 Gurgaon
237                  3 BHK Flat in Sector 102 Gurgaon
238                   3 BHK Flat in Sector 92 Gurgaon
239                   2 BHK Flat in Sector 89 Gurgaon
240                   2 BHK Flat in Sector 84 Gurgaon
241                   3 BHK Flat in Sector 73 Gurgaon
242                      2 BHK Flat in Krishna Colony
243                     3 BHK Flat in Sector 36 Sohna
244                   3 BHK Flat in Sector 71 Gurgaon
245                   3 BHK Flat in Sector 56 Gurgaon
246                   3 BHK Flat in Sector 83 Gurgaon
247                  2 BHK Flat in Sector 37D Gurgaon
248                   2 BHK Flat in Sector 65 Gurgaon
249                  2 BHK Flat in Sector 102 Gurgaon
250                   3 BHK Flat in Sector 53 Gurgaon
251                 2 BHK Flat in Ashok Vihar Phase 2
252                     2 BHK Flat in Sector-33 Sohna
253                   2 BHK Flat in Sector 65 Gurgaon
254                   2 BHK Flat in Sector 68 Gurgaon
255                   3 BHK Flat in Sector 62 Gurgaon
256                   4 BHK Flat in Sector 78 Gurgaon
257                   3 BHK Flat in Sector 83 Gurgaon
258                    3 BHK Flat in Sector 4 Gurgaon
259                   4 BHK Flat in Sector 72 Gurgaon
260                   2 BHK Flat in Sector 90 Gurgaon
261                4 BHK Flat in Sector 1 Imt Manesar
262                  3 BHK Flat in Sector 70A Gurgaon
263                   3 BHK Flat in Sector 61 Gurgaon
264                4 BHK Flat in Sector 1 Imt Manesar
265                   2 BHK Flat in Sector 79 Gurgaon
266                   2 BHK Flat in Sector 99 Gurgaon
267                   3 BHK Flat in Sector 92 Gurgaon
268                   3 BHK Flat in Sector 70 Gurgaon
269                   2 BHK Flat in Sector 79 Gurgaon
270                  2 BHK Flat in Sector 103 Gurgaon
271                   3 BHK Flat in Sector 69 Gurgaon
272                   3 BHK Flat in Sector 82 Gurgaon
273                   2 BHK Flat in Sector 47 Gurgaon
274                  2 BHK Flat in Sector 37C Gurgaon
275                  2 BHK Flat in Sector 113 Gurgaon
276                   2 BHK Flat in Sector 70 Gurgaon
277                  2 BHK Flat in Sector 37D Gurgaon
278                   3 BHK Flat in Sector 89 Gurgaon
279                   1 BHK Flat in Sector 83 Gurgaon
280                  3 BHK Flat in Sector 99A Gurgaon
281                   3 BHK Flat in Sector 92 Gurgaon
282                   3 BHK Flat in Sector 54 Gurgaon
283                   1 BHK Flat in Sector 63 Gurgaon
284                  4 BHK Flat in Sector 110 Gurgaon
285                   3 BHK Flat in Sector 85 Gurgaon
286                                     property_name
287                  4 BHK Flat in Sector 113 Gurgaon
288                   3 BHK Flat in Sector 56 Gurgaon
289                   3 BHK Flat in Sector 65 Gurgaon
290                         3 BHK Flat in Palam Vihar
291                   3 BHK Flat in Sector 84 Gurgaon
292                   4 BHK Flat in Sector 33 Gurgaon
293                              3 BHK Flat in Kanahi
294                     2 BHK Flat in Sector-11 sohna
295                   3 BHK Flat in Sector 67 Gurgaon
296                   2 BHK Flat in Sector 62 Gurgaon
297                     2 BHK Flat in Sector-33 Sohna
298                         3 BHK Flat in DLF Phase 5
299                   3 BHK Flat in Sector 61 Gurgaon
300                               2 BHK Flat in Sohna
301                   4 BHK Flat in Sector 9A Gurgaon
302                   2 BHK Flat in Sector 85 Gurgaon
303                   3 BHK Flat in Sector 77 Gurgaon
304                   1 BHK Flat in Sector 28 Gurgaon
305                   5 BHK Flat in Sector 14 Gurgaon
306                   4 BHK Flat in Sector 86 Gurgaon
307                  3 BHK Flat in Sector 102 Gurgaon
308                   3 BHK Flat in Sector 61 Gurgaon
309                     3 BHK Flat in Nirvana Country
310                   3 BHK Flat in Sector 61 Gurgaon
311                  3 BHK Flat in Sector 102 Gurgaon
312                     3 BHK Flat in Sector-33 Sohna
313                  2 BHK Flat in Sector 103 Gurgaon
314                  4 BHK Flat in Sector 113 Gurgaon
315                  3 BHK Flat in Sector 102 Gurgaon
316                         4 BHK Flat in DLF Phase 2
317                  4 BHK Flat in Sector 111 Gurgaon
318                   2 BHK Flat in Sector 79 Gurgaon
319                   3 BHK Flat in Sector 48 Gurgaon
320                   3 BHK Flat in Sector 56 Gurgaon
321                   3 BHK Flat in Sector 65 Gurgaon
322                         3 BHK Flat in Palam Vihar
323                   3 BHK Flat in Sector 84 Gurgaon
324                   3 BHK Flat in Sector 67 Gurgaon
325                   2 BHK Flat in Sector 62 Gurgaon
326                         3 BHK Flat in DLF Phase 5
327                               2 BHK Flat in Sohna
328                   4 BHK Flat in Sector 9A Gurgaon
329                   2 BHK Flat in Sector 85 Gurgaon
330                   3 BHK Flat in Sector 77 Gurgaon
331                   1 BHK Flat in Sector 28 Gurgaon
332                   5 BHK Flat in Sector 14 Gurgaon
333                   4 BHK Flat in Sector 86 Gurgaon
334                  3 BHK Flat in Sector 102 Gurgaon
335                     3 BHK Flat in Nirvana Country
336                  3 BHK Flat in Sector 102 Gurgaon
337                  2 BHK Flat in Sector 103 Gurgaon
338                  3 BHK Flat in Sector 102 Gurgaon
339                         4 BHK Flat in DLF Phase 2
340                   2 BHK Flat in Sector 79 Gurgaon
341                   3 BHK Flat in Sector 53 Gurgaon
342                   4 BHK Flat in Sector 92 Gurgaon
343                  2 BHK Flat in Sector 70A Gurgaon
344                  3 BHK Flat in Sector 108 Gurgaon
345                  3 BHK Flat in Sector 37D Gurgaon
346                   4 BHK Flat in Sector 48 Gurgaon
347                   3 BHK Flat in Sector 83 Gurgaon
348                   3 BHK Flat in Sector 71 Gurgaon
349                               2 BHK Flat in Sohna
350                   3 BHK Flat in Sector 59 Gurgaon
351                   3 BHK Flat in Sector 92 Gurgaon
352                     2 BHK Flat in Sector-33 Sohna
353                   1 BHK Flat in Sector 67 Gurgaon
354                  2 BHK Flat in Sector 108 Gurgaon
355                  4 BHK Flat in Sector 108 Gurgaon
356                     2 BHK Flat in Sector-33 Sohna
357                   2 BHK Flat in Sector 61 Gurgaon
358                   3 BHK Flat in Sector 66 Gurgaon
359                         2 BHK Flat in Palam Vihar
360                         3 BHK Flat in Palam Vihar
361                   3 BHK Flat in Sector 67 Gurgaon
362                   3 BHK Flat in Sector 86 Gurgaon
363                  3 BHK Flat in Sector 102 Gurgaon
364                   3 BHK Flat in Sector 30 Gurgaon
365                         3 BHK Flat in DLF Phase 4
366                   3 BHK Flat in Sector 67 Gurgaon
367                   4 BHK Flat in Sector 22 Gurgaon
368                   2 BHK Flat in Sector 92 Gurgaon

In [28]:
f_dc.isnull().sum()

property_name        0
link                 0
society              0
price               20
area_persqft        13
areaWithType        19
bedRoom             19
bathroom            19
balcony             19
additionalRoom       0
address             25
floorNum            20
facing             899
agePossession       20
nearbyLocations    113
description         19
furnishDetails     824
features           432
rating             351
property_id         19
dtype: int64

In [29]:
f_dc['floorNum']

0              4th   of 4 Floors
1              1st   of 3 Floors
2            12nd   of 14 Floors
3              2nd   of 4 Floors
4              5th   of 8 Floors
5              3rd   of 3 Floors
6             5th   of 25 Floors
7            14th   of 27 Floors
8              2nd   of 3 Floors
9            31st   of 40 Floors
10             1st   of 4 Floors
11            4th   of 13 Floors
12            4th   of 15 Floors
13            3rd   of 20 Floors
14           13rd   of 13 Floors
15           25th   of 25 Floors
16            Ground of 1 Floors
17           Ground of 14 Floors
18           11st   of 14 Floors
19           12nd   of 13 Floors
20             4th   of 4 Floors
21           11st   of 22 Floors
22             4th   of 4 Floors
23           Ground of 14 Floors
24           10th   of 25 Floors
25            Ground of 1 Floors
26             3rd   of 3 Floors
27           20th   of 20 Floors
28            5th   of 17 Floors
29            4th   of 12 Floors
30             4th   of 4 Floors
31             1st   of 4 Floors
32           12nd   of 12 Floors
33            8th   of 12 Floors
34           20th   of 20 Floors
35             8th   of 8 Floors
36           21st   of 24 Floors
37           Ground of 11 Floors
38            6th   of 19 Floors
39            1st   of 19 Floors
40             1st   of 3 Floors
41           12nd   of 17 Floors
42            6th   of 24 Floors
43            1st   of 25 Floors
44             2nd   of 4 Floors
45             1st   of 4 Floors
46            9th   of 29 Floors
47             5th   of 8 Floors
48           18th   of 32 Floors
49           29th   of 31 Floors
50             3rd   of 5 Floors
51            3rd   of 26 Floors
52            5th   of 18 Floors
53             1st   of 4 Floors
54            9th   of 12 Floors
55            6th   of 10 Floors
56             2nd   of 4 Floors
57           14th   of 14 Floors
58            1st   of 11 Floors
59            8th   of 14 Floors
60             2nd   of 2 Floors
61           12nd   of 12 Floors
62            4th   of 14 Floors
63            1st   of 18 Floors
64            7th   of 19 Floors
65             3rd   of 4 Floors
66            5th   of 20 Floors
67            9th   of 15 Floors
68           14th   of 17 Floors
69           14th   of 14 Floors
70           15th   of 20 Floors
71            6th   of 14 Floors
72            6th   of 14 Floors
73            2nd   of 12 Floors
74            3rd   of 11 Floors
75             2nd   of 4 Floors
76            4th   of 13 Floors
77             3rd   of 4 Floors
78            6th   of 14 Floors
79            8th   of 13 Floors
80             2nd   of 4 Floors
81             4th   of 4 Floors
82           Ground of 14 Floors
83           11st   of 11 Floors
84             1st   of 3 Floors
85           11st   of 13 Floors
86           21st   of 41 Floors
87            4th   of 13 Floors
88             2nd   of 5 Floors
89             2nd   of 3 Floors
90             4th   of 4 Floors
91           32nd   of 32 Floors
92             2nd   of 4 Floors
93             2nd   of 2 Floors
94             2nd   of 2 Floors
95           11st   of 11 Floors
96           23rd   of 26 Floors
97            6th   of 12 Floors
98            9th   of 20 Floors
99             1st   of 4 Floors
100           5th   of 15 Floors
101            43   of 47 Floors
102            1st   of 1 Floors
103            1st   of 4 Floors
104           1st   of 13 Floors
105          11st   of 12 Floors
106          14th   of 24 Floors
107           9th   of 30 Floors
108           8th   of 14 Floors
109            9th   of 9 Floors
110           2nd   of 12 Floors
111           4th   of 14 Floors
112          32nd   of 55 Floors
113            43   of 47 Floors
114           2nd   of 19 Floors
115            3rd   of 4 Floors
116           8th   of 22 Floors
117            3rd   of 4 Floors
118          20th   of 32 Floors
119           2nd   of 17 Floors
120        Basement of 28 Floors
121           4th   of 10 Floors
122           Ground of 4 Floors
123            3rd   of 4 Floors
124            4th   of 8 Floors
125            3rd   of 4 Floors
126           6th   of 20 Floors
127          13rd   of 13 Floors
128          13rd   of 13 Floors
129          16th   of 16 Floors
130            3rd   of 4 Floors
131           Ground of 1 Floors
132          11st   of 14 Floors
133           2nd   of 14 Floors
134          12nd   of 12 Floors
135            2nd   of 4 Floors
136           1st   of 18 Floors
137           4th   of 12 Floors
138          11st   of 13 Floors
139           5th   of 17 Floors
140           1st   of 25 Floors
141          12nd   of 16 Floors
142          16th   of 18 Floors
143            6th   of 6 Floors
144            2nd   of 2 Floors
145            3rd   of 4 Floors
146          11st   of 25 Floors
147          10th   of 18 Floors
148           2nd   of 25 Floors
149            4th   of 4 Floors
150          19th   of 41 Floors
151            1st   of 3 Floors
152            8th   of 8 Floors
153          18th   of 19 Floors
154          10th   of 16 Floors
155           7th   of 20 Floors
156           2nd   of 14 Floors
157          10th   of 10 Floors
158           5th   of 12 Floors
159          10th   of 20 Floors
160          20th   of 34 Floors
161          20th   of 22 Floors
162            3rd   of 4 Floors
163          13rd   of 14 Floors
164           3rd   of 19 Floors
165           7th   of 18 Floors
166            4th   of 4 Floors
167           4th   of 14 Floors
168            2nd   of 4 Floors
169           2nd   of 25 Floors
170           4th   of 14 Floors
171           3rd   of 19 Floors
172            1st   of 1 Floors
173            2nd   of 4 Floors
174          11st   of 15 Floors
175          11st   of 21 Floors
176          16th   of 22 Floors
177           8th   of 10 Floors
178           1st   of 35 Floors
179          18th   of 25 Floors
180           8th   of 15 Floors
181                          NaN
182           2nd   of 16 Floors
183          17th   of 17 Floors
184          23rd   of 28 Floors
185          10th   of 18 Floors
186          30th   of 32 Floors
187            4th   of 4 Floors
188            2nd   of 3 Floors
189           Ground of 3 Floors
190          Ground of 14 Floors
191            1st   of 4 Floors
192            1st   of 1 Floors
193          11st   of 36 Floors
194          11st   of 13 Floors
195           Ground of 3 Floors
196          19th   of 19 Floors
197          28th   of 28 Floors
198            4th   of 4 Floors
199            9th   of 9 Floors
200            7th   of 7 Floors
201         Basement of 4 Floors
202          15th   of 15 Floors
203           2nd   of 34 Floors
204          Ground of 14 Floors
205           9th   of 10 Floors
206           1st   of 15 Floors
207            1st   of 1 Floors
208           4th   of 34 Floors
209           4th   of 18 Floors
210           3rd   of 15 Floors
211            1st   of 4 Floors
212           1st   of 19 Floors
213     Lower Ground of 4 Floors
214          13rd   of 13 Floors
215           4th   of 40 Floors
216           6th   of 18 Floors
217          20th   of 47 Floors
218          27th   of 48 Floors
219            6th   of 7 Floors
220          33rd   of 48 Floors
221          35th   of 35 Floors
222          26th   of 47 Floors
223           Ground of 1 Floors
224            2nd   of 4 Floors
225           4th   of 14 Floors
226          10th   of 17 Floors
227          11st   of 14 Floors
228          10th   of 22 Floors
229          Ground of 24 Floors
230           3rd   of 12 Floors
231           7th   of 25 Floors
232           8th   of 14 Floors
233            2nd   of 4 Floors
234           3rd   of 18 Floors
235            1st   of 4 Floors
236           9th   of 14 Floors
237          14th   of 15 Floors
238            4th   of 4 Floors
239           8th   of 25 Floors
240          10th   of 14 Floors
241           3rd   of 14 Floors
242            3rd   of 4 Floors
243            2nd   of 4 Floors
244           3rd   of 14 Floors
245            7th   of 7 Floors
246            2nd   of 4 Floors
247           3rd   of 15 Floors
248           8th   of 34 Floors
249          12nd   of 14 Floors
250           8th   of 42 Floors
251            1st   of 4 Floors
252           1st   of 22 Floors
253          26th   of 34 Floors
254          21st   of 29 Floors
255           8th   of 32 Floors
256           2nd   of 14 Floors
257           1st   of 12 Floors
258            2nd   of 4 Floors
259          39th   of 40 Floors
260           1st   of 14 Floors
261           8th   of 10 Floors
262            2nd   of 3 Floors
263            3rd   of 4 Floors
264            7th   of 9 Floors
265           4th   of 15 Floors
266          22nd   of 24 Floors
267          14th   of 20 Floors
268          11st   of 15 Floors
269          17th   of 17 Floors
270           3rd   of 12 Floors
271          12nd   of 13 Floors
272           8th   of 19 Floors
273           3rd   of 14 Floors
274          14th   of 14 Floors
275            7th   of 7 Floors
276           9th   of 15 Floors
277           2nd   of 17 Floors
278            3rd   of 3 Floors
279            6th   of 6 Floors
280          16th   of 16 Floors
281          12nd   of 12 Floors
282            1st   of 1 Floors
283            4th   of 4 Floors
284          17th   of 17 Floors
285           7th   of 26 Floors
286                     floorNum
287          11st   of 30 Floors
288            4th   of 8 Floors
289           1st   of 14 Floors
290           6th   of 14 Floors
291            1st   of 3 Floors
292          17th   of 17 Floors
293            1st   of 7 Floors
294          16th   of 18 Floors
295          19th   of 40 Floors
296          31st   of 32 Floors
297          14th   of 22 Floors
298           5th   of 19 Floors
299            2nd   of 4 Floors
300            1st   of 4 Floors
301           1st   of 10 Floors
302          15th   of 32 Floors
303            1st   of 7 Floors
304            1st   of 2 Floors
305            2nd   of 3 Floors
306          11st   of 14 Floors
307           9th   of 26 Floors
308          33rd   of 42 Floors
309          14th   of 18 Floors
310            4th   of 4 Floors
311           5th   of 14 Floors
312          18th   of 18 Floors
313           1st   of 14 Floors
314          20th   of 23 Floors
315           9th   of 14 Floors
316          18th   of 19 Floors
317           8th   of 32 Floors
318           4th   of 15 Floors
319           9th   of 17 Floors
320            4th   of 8 Floors
321           1st   of 14 Floors
322           6th   of 14 Floors
323            1st   of 3 Floors
324          19th   of 40 Floors
325          31st   of 32 Floors
326           5th   of 19 Floors
327            1st   of 4 Floors
328           1st   of 10 Floors
329          15th   of 32 Floors
330            1st   of 7 Floors
331            1st   of 2 Floors
332            2nd   of 3 Floors
333          11st   of 14 Floors
334           9th   of 26 Floors
335          14th   of 18 Floors
336           5th   of 14 Floors
337           1st   of 14 Floors
338           9th   of 14 Floors
339          18th   of 19 Floors
340           4th   of 15 Floors
341           1st   of 44 Floors
342          20th   of 20 Floors
343          24th   of 31 Floors
344           2nd   of 15 Floors
345            4th   of 4 Floors
346          14th   of 14 Floors
347           9th   of 16 Floors
348          14th   of 15 Floors
349           4th   of 14 Floors
350          26th   of 30 Floors
351           2nd   of 16 Floors
352          14th   of 24 Floors
353          17th   of 17 Floors
354           2nd   of 14 Floors
355          25th   of 25 Floors
356           9th   of 22 Floors
357            4th   of 4 Floors
358           6th   of 17 Floors
359           5th   of 14 Floors
360           4th   of 14 Floors
361          14th   of 21 Floors
362          15th   of 19 Floors
363           7th   of 14 Floors
364            2nd   of 4 Floors
365          16th   of 20 Floors
366          24th   of 51 Floors
367          10th   of 20 Floors
368            2nd   of 4 Floors
369           2nd   of 12 Floors
370           2nd   of 24 Floors
371           1st   of 19 Floors
372           8th   of 18 Floors
373          12nd   of 22 Floors
374          18th   of 19 Floors
375            1st   of 4 Floors
376           2nd   of 36 Floors
377            3rd   of 4 Floors
378          11st   of 11 Floors
379           7th   of 20 Floors
380           5th   of 18 Floors
381           6th   of 12 Floors
382          19th   of 31 Floors
383          25th   of 25 Floors
384          10th   of 10 Floors
385          10th   of 10 Floors
386            3rd   of 9 Floors
387           8th   of 14 Floors
388           5th   of 12 Floors
389           4th   of 22 Floors
390           1st   of 35 Floors
391          10th   of 14 Floors
392          16th   of 24 Floors
393          10th   of 14 Floors
394            3rd   of 8 Floors
395          17th   of 19 Floors
396           9th   of 14 Floors
397          11st   of 26 Floors
398          19th   of 20 Floors
399          Ground of 16 Floors
400          Ground of 23 Floors
401           8th   of 26 Floors
402           4th   of 11 Floors
403          30th   of 32 Floors
404          16th   of 51 Floors
405          18th   of 21 Floors
406           2nd   of 10 Floors
407           7th   of 10 Floors
408            2nd   of 4 Floors
409          10th   of 10 Floors
410           9th   of 12 Floors
411           6th   of 10 Floors
412          14th   of 29 Floors
413          25th   of 36 Floors
414           7th   of 23 Floors
415           4th   of 14 Floors
416            7th   of 9 Floors
417          18th   of 32 Floors
418          12nd   of 17 Floors
419            3rd   of 4 Floors
420          21st   of 28 Floors
421          14th   of 28 Floors
422           5th   of 25 Floors
423           3rd   of 19 Floors
424          19th   of 24 Floors
425          10th   of 14 Floors
426            5th   of 9 Floors
427          10th   of 30 Floors
428           7th   of 14 Floors
429          11st   of 20 Floors
430           2nd   of 17 Floors
431            2nd   of 4 Floors
432           7th   of 14 Floors
433           6th   of 14 Floors
434          11st   of 17 Floors
435           9th   of 14 Floors
436            4th   of 4 Floors
437          14th   of 20 Floors
438            5th   of 5 Floors
439            1st   of 4 Floors
440          16th   of 27 Floors
441           1st   of 10 Floors
442          18th   of 32 Floors
443           6th   of 16 Floors
444           8th   of 13 Floors
445            4th   of 4 Floors
446           7th   of 27 Floors
447            9th   of 9 Floors
448            3rd   of 4 Floors
449          11st   of 18 Floors
450          17th   of 25 Floors
451           7th   of 42 Floors
452           5th   of 30 Floors
453          16th   of 32 Floors
454           2nd   of 16 Floors
455           8th   of 29 Floors
456            2nd   of 8 Floors
457           3rd   of 32 Floors
458           6th   of 26 Floors
459          Ground of 14 Floors
460           2nd   of 12 Floors
461          15th   of 40 Floors
462          10th   of 25 Floors
463          11st   of 30 Floors
464          10th   of 15 Floors
465           4th   of 12 Floors
466           3rd   of 18 Floors
467           9th   of 19 Floors
468           8th   of 16 Floors
469           7th   of 12 Floors
470           5th   of 12 Floors
471           7th   of 14 Floors
472           7th   of 14 Floors
473           9th   of 14 Floors
474           2nd   of 20 Floors
475           5th   of 18 Floors
476          11st   of 20 Floors
477           8th   of 11 Floors
478           7th   of 17 Floors
479          20th   of 26 Floors
480          10th   of 12 Floors
481           7th   of 29 Floors
482          10th   of 51 Floors
483          16th   of 21 Floors
484           8th   of 21 Floors
485           1st   of 14 Floors
486          18th   of 30 Floors
487          15th   of 30 Floors
488          25th   of 30 Floors
489           5th   of 29 Floors
490           9th   of 26 Floors
491           5th   of 26 Floors
492           7th   of 26 Floors
493           7th   of 26 Floors
494           7th   of 26 Floors
495          12nd   of 30 Floors
496           5th   of 15 Floors
497           4th   of 10 Floors
498           6th   of 10 Floors
499            3rd   of 6 Floors
500          10th   of 18 Floors
501          15th   of 28 Floors
502          15th   of 28 Floors
503          10th   of 14 Floors
504           9th   of 28 Floors
505          10th   of 15 Floors
506          10th   of 21 Floors
507           9th   of 12 Floors
508           Ground of 4 Floors
509            1st   of 2 Floors
510          11st   of 12 Floors
511          17th   of 24 Floors
512           1st   of 26 Floors
513          Ground of 18 Floors
514           7th   of 14 Floors
515            5th   of 8 Floors
516          12nd   of 29 Floors
517          14th   of 29 Floors
518          14th   of 29 Floors
519           9th   of 21 Floors
520          19th   of 29 Floors
521           8th   of 14 Floors
522          14th   of 29 Floors
523           8th   of 14 Floors
524            2nd   of 5 Floors
525           9th   of 13 Floors
526           5th   of 14 Floors
527          Ground of 14 Floors
528            6th   of 8 Floors
529          10th   of 19 Floors
530           6th   of 10 Floors
531           8th   of 18 Floors
532           9th   of 24 Floors
533           9th   of 26 Floors
534          12nd   of 17 Floors
535          11st   of 16 Floors
536           6th   of 16 Floors
537          15th   of 39 Floors
538           7th   of 12 Floors
539           8th   of 19 Floors
540           8th   of 26 Floors
541           3rd   of 26 Floors
542          10th   of 26 Floors
543           1st   of 26 Floors
544           4th   of 26 Floors
545           5th   of 12 Floors
546           2nd   of 12 Floors
547          20th   of 40 Floors
548          13rd   of 40 Floors
549           8th   of 40 Floors
550           8th   of 19 Floors
551          16th   of 19 Floors
552          12nd   of 18 Floors
553          10th   of 19 Floors
554           6th   of 15 Floors
555          16th   of 19 Floors
556           8th   of 16 Floors
557          12nd   of 15 Floors
558          12nd   of 18 Floors
559           5th   of 22 Floors
560           9th   of 42 Floors
561           7th   of 14 Floors
562           7th   of 12 Floors
563           7th   of 12 Floors
564           5th   of 16 Floors
565           8th   of 31 Floors
566           7th   of 21 Floors
567           5th   of 29 Floors
568           9th   of 30 Floors
569          11st   of 29 Floors
570          10th   of 19 Floors
571           6th   of 31 Floors
572            3rd   of 9 Floors
573          22nd   of 30 Floors
574           5th   of 20 Floors
575          15th   of 29 Floors
576           5th   of 14 Floors
577          Ground of 14 Floors
578           6th   of 14 Floors
579           1st   of 24 Floors
580            2nd   of 8 Floors
581          12nd   of 19 Floors
582          12nd   of 25 Floors
583           6th   of 17 Floors
584           8th   of 18 Floors
585            4th   of 5 Floors
586           5th   of 25 Floors
587           2nd   of 19 Floors
588          20th   of 30 Floors
589          12nd   of 14 Floors
590          18th   of 19 Floors
591           2nd   of 26 Floors
592           3rd   of 15 Floors
593           3rd   of 19 Floors
594          18th   of 51 Floors
595           7th   of 27 Floors
596          17th   of 19 Floors
597           8th   of 14 Floors
598           2nd   of 19 Floors
599           8th   of 19 Floors
600           9th   of 30 Floors
601           3rd   of 18 Floors
602          12nd   of 23 Floors
603          10th   of 28 Floors
604            2nd   of 5 Floors
605          Ground of 21 Floors

In [30]:
f_dc['floorNum']=f_dc['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0')

In [31]:
f_dc['floorNum']=f_dc['floorNum'].str.extract(r'(\d+)')

In [32]:
f_dc.isnull().sum()

property_name        0
link                 0
society              0
price               20
area_persqft        13
areaWithType        19
bedRoom             19
bathroom            19
balcony             19
additionalRoom       0
address             25
floorNum            21
facing             899
agePossession       20
nearbyLocations    113
description         19
furnishDetails     824
features           432
rating             351
property_id         19
dtype: int64

In [33]:
f_dc.shape

(3027, 20)

In [34]:
f_dc[f_dc['price']=='Price on Request']

,property_name,link,society,price,area_persqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
25,5 BHK Flat in Sector 1 Gurgaon,https://www.99acres.com/5-bhk-bedroom-apartmen...,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5,1,No,not avilable,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",0,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN,Z68804716
1645,4 BHK Flat in Sector 50 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4,4,3,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5...",S65406842
1973,1 BHK Flat in Sector 31 Gurgaon,https://www.99acres.com/1-bhk-bedroom-apartmen...,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1,1,1,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of...",Q70122610
2055,2 BHK Flat in Sector 79 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2,2,No,not avilable,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5...",M69984000
2358,2 BHK Flat in Sector 37D Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2,1,1,not avilable,"Sector 37D Gurgaon, Gurgaon, Haryana",13,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",L69416788
2523,2 BHK Flat in Sector 95A Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2,2,2,not avilable,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of...",A69074608
2550,3 BHK Flat in Sector-2 Sohna,https://www.99acres.com/3-bhk-bedroom-apartmen...,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3,3,3,not avilable,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN,X66482366
2641,2 BHK Flat in Sector 95A Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2,2,2,not avilable,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ...",A69074608
2960,3 BHK Flat in Sector 104 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3,3,3,not avilable,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of...",F62164440
2973,4 BHK Flat in Gwal Pahari,https://www.99acres.com/4-bhk-bedroom-apartmen...,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4,5,1,not avilable,"Gwal Pahari, Gurgaon, Haryana",17,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN,H28672425
2974,4 BHK Flat in Sector 95 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4,4,3+,not avilable,"Sector 95 Gurgaon, Gurgaon, Haryana",0,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5...",E22752179

In [35]:
# sector column
f_dc['sector']=f_dc['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip().str.lower()

In [36]:
f_dc['sector'].value_counts()

sector
sohna                            160
sector 102                       113
sector 85                        110
sector 92                        100
sector 69                         92
sector 90                         90
sector 65                         89
sector 81                         87
sector 79                         82
sector 83                         68
sector 37d                        66
sector 104                        66
sector 86                         63
sector 107                        61
sector 95                         58
sector 89                         55
sector 37c                        55
sector 108                        55
sector 70                         53
sector 109                        52
sector 84                         51
sector-33 sohna                   49
sector 56                         44
sector 113                        43
sector 67                         42
sector 61                         41
sector 103                        41
sector 70a                        40
sector 106                        37
sector 99a                        33
sector 82                         32
sector 68                         30
sector 49                         30
sector 66                         29
sector 77                         29
palam vihar                       28
sector 48                         28
sector 71                         27
sector 72                         25
sector 88a                        24
nirvana country                   22
sector 67a                        21
sector 112                        21
sector 111                        21
sector 54                         20
sector 82a                        19
sector 78                         19
sector 74                         18
sector 22                         18
sector 99                         17
sector 62                         17
sector 63a                        16
sector 110                        15
gwal pahari                       15
sector 91                         15
sector 1 imt manesar              14
dlf phase 4                       14
sector 60                         14
sector 53                         13
sector 36a                        13
sector 63                         13
dlf phase 5                       13
sector 76                         12
sector 52                         11
sector 93                         11
sector 95a                        11
sector 9a                         11
sector 1a imt manesar             10
sector 33                          9
sector 47                          8
sector 59                          8
sector 89 a                        8
sector 43                          7
mehrauli  road                     7
sector 3                           7
sector 58                          7
dwarka expressway                  7
sector 36 sohna                    6
sector 50                          6
laxman vihar                       6
sector 51                          6
sector 39                          5
adarsh nagar                       5
chakkarpur                         5
sector 80                          5
sector 1                           5
sector 2                           5
sector 30                          5
sector 10a                         5
ashok vihar phase 2                5
sushant lok phase 1                5
dlf phase 3                        4
new                                4
sector 31                          4
new palam vihar                    4
dlf phase 2                        4
valley view estate                 4
sector 110 a                       3
sector 88b                         3
sector 55                          3
manesar                            3
sector 36                          3
imt manesar                        3
sector 12                          3
golf course ext road               3
sector 28                          3
mg road                            3
sohna road                         3
dayanand colony                    3
sector-2 sohna                     3
ashok vihar                        3
sector 11                          2
sector 23a                         2
shanti nagar                       2
sushant lok                        2
sector 21                          2
samaspur                           2
rajendra park                      2
surat nagar 1                      2
sispal vihar                       2
shankar vihar                      2
dharam colony                      2
sector 105                         2
sector 24                          2
sector 32                          2
sushant lok phase 3                2
krishna colony                     2
godrej aria , sector 79 ,          2
sector 57                          2
sector 73                          2
sector 4                           2
iffco chowk                        2
malibu town                        2
sector 7                           2
sector-11 sohna                    2
sector 14                          2
sector 15                          2
block a surya vihar                2
ambience island                    2
ashok vihar phase 3 extension      2
sector 45                          2
suncity                            2
patel nagar                        1
garauli kalan                      1
nirvana country pocket h           1
rajiv colony                       1
sector 12a                         1
sector 15 part 1                   1
new palam vihar phase 2            1
saroop garden rajendra park        1
sector-35 sohna                    1
bhondsi                            1
palam vihar extension              1
sector 4 urban estate              1
bptp                               1
sector-7 hous                      1
south city 1                       1
sector 9                           1
c block sushant lok phase 1        1
sector 40                          1
bhawani enclave                    1
sai kunj                           1
sector 5                           1
near sector 1 market               1
civil l                            1
new colony, sector 7               1
lajpat nagar                       1
sector 38                          1
heritage city                      1
surya vihar                        1
near pataudi chowk                 1
cyber city                         1
new colony                         1
subhash nagar                      1
ats marigold                       1
kanahi                             1
sector 37a                         1
sector 41                          1
carterpuri village                 1
golf course road                   1
laxman vihar phase 2               1
sultanpur                          1
faridabad road                     1
sector 5 chowk                     1
old delhi road, opp sector-14      1
sector-5 sohna                     1
Name: count, dtype: int64

In [37]:
f_dc['sector']=f_dc['sector'].str.replace('palam vihar','sector 2')
f_dc['sector']=f_dc['sector'].str.replace('nirvana country','sector 50')
f_dc['sector']=f_dc['sector'].str.replace('gwal pahari','sector 2')

In [38]:
f_dc['sector'].value_counts()

sector
sohna                            160
sector 102                       113
sector 85                        110
sector 92                        100
sector 69                         92
sector 90                         90
sector 65                         89
sector 81                         87
sector 79                         82
sector 83                         68
sector 37d                        66
sector 104                        66
sector 86                         63
sector 107                        61
sector 95                         58
sector 108                        55
sector 89                         55
sector 37c                        55
sector 70                         53
sector 109                        52
sector 84                         51
sector-33 sohna                   49
sector 2                          48
sector 56                         44
sector 113                        43
sector 67                         42
sector 103                        41
sector 61                         41
sector 70a                        40
sector 106                        37
sector 99a                        33
sector 82                         32
sector 68                         30
sector 49                         30
sector 66                         29
sector 77                         29
sector 48                         28
sector 50                         28
sector 71                         27
sector 72                         25
sector 88a                        24
sector 67a                        21
sector 111                        21
sector 112                        21
sector 54                         20
sector 78                         19
sector 82a                        19
sector 74                         18
sector 22                         18
sector 99                         17
sector 62                         17
sector 63a                        16
sector 110                        15
sector 91                         15
sector 60                         14
dlf phase 4                       14
sector 1 imt manesar              14
sector 53                         13
dlf phase 5                       13
sector 36a                        13
sector 63                         13
sector 76                         12
sector 52                         11
sector 93                         11
sector 95a                        11
sector 9a                         11
sector 1a imt manesar             10
sector 33                          9
sector 59                          8
sector 47                          8
sector 89 a                        8
sector 58                          7
sector 3                           7
sector 43                          7
dwarka expressway                  7
mehrauli  road                     7
sector 36 sohna                    6
sector 51                          6
laxman vihar                       6
sector 39                          5
adarsh nagar                       5
chakkarpur                         5
sushant lok phase 1                5
sector 80                          5
ashok vihar phase 2                5
sector 1                           5
sector 10a                         5
sector 30                          5
new sector 2                       4
sector 31                          4
new                                4
dlf phase 3                        4
dlf phase 2                        4
valley view estate                 4
manesar                            3
sohna road                         3
sector-2 sohna                     3
imt manesar                        3
golf course ext road               3
mg road                            3
sector 28                          3
sector 36                          3
sector 12                          3
ashok vihar                        3
sector 55                          3
dayanand colony                    3
sector 88b                         3
sector 110 a                       3
sector 23a                         2
sispal vihar                       2
rajendra park                      2
shanti nagar                       2
sector 21                          2
sushant lok                        2
dharam colony                      2
sector 105                         2
surat nagar 1                      2
sector 24                          2
samaspur                           2
shankar vihar                      2
sector 11                          2
sector 32                          2
sushant lok phase 3                2
krishna colony                     2
godrej aria , sector 79 ,          2
sector 57                          2
sector 73                          2
sector 4                           2
iffco chowk                        2
malibu town                        2
sector 7                           2
sector-11 sohna                    2
sector 14                          2
sector 15                          2
block a surya vihar                2
ambience island                    2
ashok vihar phase 3 extension      2
sector 45                          2
suncity                            2
patel nagar                        1
garauli kalan                      1
sector 50 pocket h                 1
rajiv colony                       1
sector 12a                         1
sector 15 part 1                   1
new sector 2 phase 2               1
saroop garden rajendra park        1
sector-35 sohna                    1
bhondsi                            1
sector 2 extension                 1
sector 4 urban estate              1
bptp                               1
sector-7 hous                      1
south city 1                       1
sector 9                           1
c block sushant lok phase 1        1
sector 40                          1
bhawani enclave                    1
sai kunj                           1
sector 5                           1
near sector 1 market               1
civil l                            1
new colony, sector 7               1
lajpat nagar                       1
sector 38                          1
heritage city                      1
surya vihar                        1
near pataudi chowk                 1
cyber city                         1
new colony                         1
subhash nagar                      1
ats marigold                       1
kanahi                             1
sector 37a                         1
sector 41                          1
carterpuri village                 1
golf course road                   1
laxman vihar phase 2               1
sultanpur                          1
faridabad road                     1
sector 5 chowk                     1
old delhi road, opp sector-14      1
sector-5 sohna                     1
Name: count, dtype: int64

In [39]:
f_dc['sector']=f_dc['sector'].str.strip()

In [40]:
f_dc[(f_dc['sector'] == 'Sector 1') & (f_dc['bedRoom'] == '5')]

Empty DataFrame
Columns: [property_name, link, society, price, area_persqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating, property_id, sector]
Index: []

In [41]:
f_dc[(f_dc['sector'] == 'Sector 50') & (f_dc['bedRoom'] == '4')]

Empty DataFrame
Columns: [property_name, link, society, price, area_persqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating, property_id, sector]
Index: []

we don't fill median value instead to price on request area with type feature also get important here.

In [42]:
# converting to crore
def change_price(l):
    if type(l)==float:# for NaN values
        return l
    elif len(l)==2:
        if l[1]=='Lac':
            return round(float(l[0])*0.01,2)
        elif l[1]=='Crore':
            return round(float(l[0]),2)
    else:
        return ''.join(l)

In [43]:
f_dc['price']=f_dc['price'].str.split(' ').apply(change_price)

In [44]:
l=f_dc['area_persqft'].str.split(',')[0]
float(''.join(l))

5000.0

In [45]:
def remove_comma(x):
    if type(x)==float:# for nan values
        return x
    else:
        l=x.split(',')
        return float(''.join(l))

In [46]:
f_dc[f_dc['area_persqft']=='']

,property_name,link,society,price,area_persqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id,sector
286,property_name,link,society,price,,areaWithType,,,balcony,additionalRoom,address,NaN,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id,NaN

In [47]:
f_dc.iloc[286]

property_name        property_name
link                          link
society                    society
price                        price
area_persqft
areaWithType          areaWithType
bedRoom
bathroom
balcony                    balcony
additionalRoom      additionalRoom
address                    address
floorNum                       NaN
facing                      facing
agePossession        agePossession
nearbyLocations    nearbyLocations
description            description
furnishDetails      furnishDetails
features                  features
rating                      rating
property_id            property_id
sector                         NaN
Name: 286, dtype: object

In [48]:
f_dc.drop(index=286,axis=0,inplace=True)

In [49]:
f_dc['area_persqft']=f_dc['area_persqft'].apply(remove_comma)

In [50]:
f_dc.sample(5)

,property_name,link,society,price,area_persqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id,sector
109,1 BHK Flat in Sector 109 Gurgaon,https://www.99acres.com/1-bhk-bedroom-apartmen...,conscient one,1.7,17617.0,Built Up area: 965 (89.65 sq.m.)Carpet area: 6...,1,1,2,not avilable,"Sector 109, Sector 109 Gurgaon, Gurgaon, Haryana",9,NaN,undefined,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Best in class property available at sector 109...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment5 out of 5', 'Safety4.5 out of 5'...",C68597238,sector 109
2091,3 BHK Flat in Sector 74 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,m3m skywalk,2.7,13379.0,Super Built up area 2018(187.48 sq.m.),3,3,3,Store Room,"1305, Sector 74 Gurgaon, Gurgaon, Haryana",13,NaN,0 to 1 Year Old,"['Omaxe Gurgaon Mall', 'Omaxe Celebration Mall...",Spacious room\n3 floor mall inside the project...,[],"['Security / Fire Alarm', 'Power Back-up', 'In...",NaN,P69918002,sector 74
1833,3 BHK Flat in Sector 49 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,vatika city,1.69,8622.0,Carpet area: 1960 (182.09 sq.m.),3,3,3,Pooja Room,"Emilia, Sector 49 Gurgaon, Gurgaon, Haryana",3,North,5 to 10 Year Old,"['BOB ATM', 'PNB ATM', 'HDFC bank ATM', 'YES b...","A 3 bhk flat in sector-49 gurgaon, gurgaon is ...",NaN,"['Water purifier', 'Power Back-up', 'Feng Shui...","['Green Area5 out of 5', 'Construction4 out of...",R61913142,sector 49
793,3 BHK Flat in Sector 86 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,dlf new town heights,1.25,6476.0,Super Built up area 1930(179.3 sq.m.),3,4,3+,"Pooja Room,Servant Room","Lower Floor And East Facing, Sector 86 Gurgaon...",2,South-West,1 to 5 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...",Dlf new town heights sector 86Ready to move\nH...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4.5 out ...",L43236671,sector 86
1281,3 BHK Flat in Sector 77 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,emaar mgf palm hills,1.08,5400.0,Super Built up area 2000(185.81 sq.m.),3,4,3+,"Study Room,Servant Room,Others","Sector 77, Sector 77 Gurgaon, Gurgaon, Haryana",5,South-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Soh...",It is basic price advertisement prices depends...,"['1 Exhaust Fan', '1 Stove', '5 AC', '1 Modula...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4.5 out ...",K69722888,sector 77

In [51]:
def create(price,area_persqft):
    if isinstance(price,float):
        return round((price*10000000)/area_persqft,3)
    else:
        return np.nan

In [52]:
f_dc['area'] = f_dc.apply(lambda row: create(row['price'], row['area_persqft']), axis=1)

In [53]:
f_dc.sample(5)

,property_name,link,society,price,area_persqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id,sector,area
2720,2 BHK Flat in Sector 79 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,supertech araville,0.71,6061.0,Super Built up area 1295(120.31 sq.m.)Carpet a...,2,2,3+,Others,"E 1706, Sector 79 Gurgaon, Gurgaon, Haryana",17,North,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",This is your chance to own a 2 bhk residential...,"['2 Wardrobe', '2 Geyser', '1 Light', '2 AC', ...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Safety4 out of 5', 'Lifestyle3 out of 5', 'E...",Y61729236,sector 79,1171.424
1308,1 BHK Flat in Sector 95 Gurgaon,https://www.99acres.com/1-bhk-bedroom-apartmen...,ramsons kshitij,0.18,544.0,Carpet area: 3212 (298.4 sq.m.),1,1,1,not avilable,"Sector 95 Gurgaon, Gurgaon, Haryana",12,North-East,1 to 5 Year Old,"['Bangali Clinic', 'Yadav Clinic', 'Dr. J. S. ...","Ambitious, personable agent with 15 years of e...",NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area4 out of 5', 'Construction4 out of...",X70174042,sector 95,3308.824
1396,3 BHK Flat in Sector 70 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,shree vardhman victoria,1.62,8307.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3,5,3,Servant Room,"123, Sector 70 Gurgaon, Gurgaon, Haryana",9,North,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",This 3 bhk flat is located in shree vardhman v...,NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction5 out of...",C69936836,sector 70,1950.163
556,3 BHK Flat in Nirvana Country,https://www.99acres.com/3-bhk-bedroom-apartmen...,the close north,2.35,11358.0,Super Built up area 2069(192.22 sq.m.)Built Up...,3,3,3,not avilable,"8,9, Nirvana Country, Gurgaon, Haryana",8,North-West,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","Available for sale in a 3 bedroom room, 3bathr...","['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of...",Y69725362,sector 50,2069.026
1723,3 BHK Flat in Sector 69 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,tulip violet,1.43,8886.0,Super Built up area 1608(149.39 sq.m.)Carpet a...,3,3,2,Pooja Room,"First Floor, Sector 69 Gurgaon, Gurgaon, Haryana",1,South-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",This lovely 3 bhk apartment/flat in sector 69 ...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction4 out of...",R69568362,sector 69,1609.273

In [54]:
f_dc.shape

(3026, 22)

In [55]:
f_dc['sector'].isnull().sum()

0

In [56]:
f_dc.drop(columns=['property_name','link','address'],inplace=True)

In [57]:
f_dc.drop(columns=['property_id','rating'],inplace=True)

In [58]:
f_dc.sample(5)

,society,price,area_persqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,sector,area
497,cghs airport apartment,1.8,6000.0,Super Built up area 3000(278.71 sq.m.)Carpet a...,4,4,3+,Store Room,4,North-West,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Standard chartered ATM...",This 4 bhk flat is located in cghs airport apa...,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",sector 47,3000.000
2228,m3m soulitude,1.25,8784.0,Carpet area: 1423 (132.2 sq.m.),3,3,2,Study Room,3,NaN,Within 6 months,"['Vatika Town Square-INXT', 'Sector 86 Road', ...",Want to sell the property relocating out of in...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",sector 89,1423.042
2525,signature global city 37d ph 2,1.36,8846.0,Built Up area: 1535 (142.61 sq.m.),3,3,3,"Pooja Room,Others",1,North-East,2025-10-01 00:00:00,"['Dwarka Expressway', 'Pataudi Road', 'Euro In...","Easy conectivity to dwarka expressway, nh8 and...",[],"['Security / Fire Alarm', 'Lift(s)', 'Maintena...",sector 37d,1537.418
2128,smart world orchard,2.5,16139.0,Built Up area: 1549 (143.91 sq.m.),3,3,1,not avilable,1,East,undefined,"['Sector 55-56 Metro station', 'Bestech Centra...",Best in class property available at sector 61 ...,NaN,NaN,sector 61,1549.043
2178,pivotal devaan,0.35,7246.0,Carpet area: 483 (44.87 sq.m.),2,2,2,not avilable,4,East,1 to 5 Year Old,"['Dwarka Expressway', 'RPS International Schoo...",Check out this 2 bhk apartment for sale in piv...,NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...",sector 84,483.025

In [59]:
f_dc['balcony'].value_counts()
# no-->0

balcony
3     977
3+    863
2     751
1     318
No     98
Name: count, dtype: int64

In [60]:
ind=f_dc[f_dc['balcony']=='No'].index
f_dc.loc[ind,'balcony']=0

In [61]:
f_dc['bathroom'].value_counts()

bathroom
2    1046
3     991
4     638
5     170
1     115
6      42
7       5
Name: count, dtype: int64

In [62]:
f_dc.to_csv('cleaned_flat.csv',index=False)