In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
house=pd.read_excel('/Users/abhijeetkashyap/Desktop/project version 1/Copy of independent-house.xlsx')

In [4]:
house.sample(5)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
136,2 Bedroom House for sale in Sector 7 Gurgaon,https://www.99acres.com/2-bhk-bedroom-independ...,NaN,2 Crore,"₹ 13,889/sq.ft.",(134 sq.m.) Plot Area,Plot area 160(133.78 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 7 Gurgaon, Gurgaon, Haryana",2 Floors,North-West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",160 square yards double story made 4 bhk house...,"['40 Light', '1 Modular Kitchen', 'No AC', 'No...","['Park', 'Visitor Parking', 'Low Density Socie...","['Environment4 out of 5', 'Lifestyle4 out of 5...",P66687786
89,5 Bedroom House for sale in Sector 109 Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,International City by Sobha Phase 1,NaN,"₹ 11,100/sq.ft.",(468-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5...",M70112048
537,4 Bedroom House for sale in Sector 6 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,Bhim Nagar Society,40 Lac,"₹ 2,500/sq.ft.",(149 sq.m.) Built-up Area,Built Up area: 1600 (148.64 sq.m.)Carpet area:...,4 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 6, Sector 6 Gurgaon, Gurgaon, Haryana",1 Floors,East,undefined,"['Dental Hospital', 'Sercare Clinic', 'Promla ...",4bhk residential house for resale in bhim naga...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",V68022174
16,9 Bedroom House for sale in DLF Phase 2,https://www.99acres.com/9-bhk-bedroom-independ...,DLF City Plots Phase 2,10.75 Crore,"₹ 29,861/sq.ft.",(334 sq.m.) Plot Area,Plot area 400(334.45 sq.m.),9 Bedrooms,9 Bathrooms,3+ Balconies,"Servant Room,Pooja Room,Store Room","DLF Phase 2, Gurgaon, Haryana",3 Floors,South-West,10+ Year Old,"['Vodafone belvedere towers metro station', 'D...",This is located in dlf phase 2 very near from ...,"['5 Fan', '1 Exhaust Fan', '3 Light', 'No AC',...","['Security / Fire Alarm', 'Private Garden / Te...","['Environment5 out of 5', 'Lifestyle5 out of 5...",U69430128
343,10 Bedroom House for sale in Bhondsi,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,1.35 Crore,"₹ 3,857/sq.ft.",(325 sq.m.) Plot Area,Plot area 3500(325.16 sq.m.),10 Bedrooms,6 Bathrooms,3+ Balconies,NaN,"Bhondsi, Gurgaon, Bhondsi, Gurgaon, Haryana",3 Floors,NaN,10+ Year Old,NaN,Check out this 10 bhk independent house for sa...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",F66612390

In [5]:
house.shape

(1095, 21)

In [6]:
house.isnull().sum()

property_name        0
link                 0
society            624
price              127
rate                41
area                 0
areaWithType       108
bedRoom            108
bathroom           108
balcony            108
additionalRoom     506
address             64
noOfFloor          128
facing             421
agePossession      108
nearbyLocations    182
description         59
furnishDetails     352
features           421
rating             188
property_id         59
dtype: int64

In [7]:
h=house.copy()

## As previously done

In [8]:
import re
h['society'] = h['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [9]:
h['bedRoom']=h['bedRoom'].str.slice(stop=-8).str.strip()

In [10]:
h['bathroom']=h['bathroom'].str.slice(stop=-9).str.strip()

In [11]:
h['balcony']=h['balcony'].str.split(' ').str.get(0)

In [12]:
h['additionalRoom']=h['additionalRoom'].fillna('not avilable')

In [13]:
h.rename(columns={'rate':'area_persqft'},inplace=True)

In [14]:
h['area_persqft']=h['area_persqft'].str.replace('₹','').str.strip().str.slice(stop=-7)

## start

In [15]:
h.sample(5)

,property_name,link,society,price,area_persqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
90,4 Bedroom House for sale in Sector 109 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,international city by sobha phase 1,NaN,"11,100",(292-358 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,not avilable,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5...",V70112044
936,4 Bedroom House for sale in Sector 48 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,vipul tatvam villa,8.25 Crore,"38,194",(293 sq.m.) Plot Area,Plot area 350(292.64 sq.m.)Built Up area: 300 ...,4,4,3+,"Servant Room,Store Room","Villa No40, Sector 48 Gurgaon, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",4bhk lexuary villa for sell tatvam villa in se...,"['1 Water Purifier', '11 Geyser', '1 Stove', '...","['Centrally Air Conditioned', 'Water purifier'...","['Environment4 out of 5', 'Safety4 out of 5', ...",L66708342
381,1 Bedroom House for sale in Hno 13 Sagar encla...,https://www.99acres.com/1-bhk-bedroom-independ...,nan,85 Lac,"8,910",(89 sq.m.) Plot Area,Plot area 106(88.63 sq.m.),1,2,No,not avilable,"Hno 13 Sagar enclave Sura, Gurgaon, Haryana",1 Floors,NaN,1 to 5 Year Old,NaN,Independent house for sale finishing required,NaN,NaN,NaN,V69225994
629,2 Bedroom House for sale in Sector 36 Sohna,https://www.99acres.com/2-bhk-bedroom-independ...,nan,65.8 Lac,"7,168",(76 sq.m.) Built-up Area,Built Up area: 823 (76.46 sq.m.),2,2,3,not avilable,"Signature Global Park Iii, Sector 36 Sohna, Gu...",4 Floors,NaN,0 to 1 Year Old,NaN,Corner unit & 2 bhk independent floor for sale...,NaN,NaN,NaN,V67079234
1084,3 Bedroom House for sale in Sushant Lok Phase 3,https://www.99acres.com/3-bhk-bedroom-independ...,nan,4.75 Crore,"28,787",(149 sq.m.) Plot Area,Plot area 1600(148.64 sq.m.)Built Up area: 170...,3,3,3,Store Room,240 Sq.Yrd Old Siplex 3 Bhk Villa In Gated Blo...,2 Floors,North-West,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...",240 sq.Yrd park facing simplex 3 bhk villa for...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '11 L...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Safety4 out of 5', ...",G70375184

In [16]:
h['noOfFloor'].value_counts()

noOfFloor
3 Floors     309
2 Floors     300
1 Floors     183
4 Floors     139
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
11 Floors      2
12 Floors      2
10 Floors      2
16 Floors      1
51 Floors      1
41 Floors      1
27 Floors      1
20 Floors      1
13 Floors      1
21 Floors      1
02 Floors      1
33 Floors      1
Name: count, dtype: int64

In [17]:
h['noOfFloor']=h['noOfFloor'].str.strip(' ').str.split('F').str.get(0)

In [18]:
def change_price(l):
    if type(l)==float:# for NaN values
        return l
    elif len(l)==2:
        if l[1]=='Lac':
            return round(float(l[0])*0.01,2)
        elif l[1]=='Crore':
            return round(float(l[0]),2)
    else:
        return ''.join(l)

In [19]:
h['price']=h['price'].str.split(' ').apply(change_price)

In [20]:
h

                                          property_name  \
0        5 Bedroom House for sale in Sector 70A Gurgaon
1      5 Bedroom House for sale in Sector 21A Faridabad
2      10 Bedroom House for sale in Sushant Lok Phase 1
3        21 Bedroom House for sale in Sector 54 Gurgaon
4      12 Bedroom House for sale in Sushant Lok Phase 1
5      20 Bedroom House for sale in Sushant Lok Phase 1
6         5 Bedroom House for sale in Sector 66 Gurgaon
7              16 Bedroom House for sale in DLF Phase 1
8               6 Bedroom House for sale in DLF Phase 2
9       3 Bedroom House for sale in Sushant Lok Phase 1
10              4 Bedroom House for sale in DLF Phase 2
11              6 Bedroom House for sale in DLF Phase 4
12             13 Bedroom House for sale in DLF Phase 3
13              5 Bedroom House for sale in DLF Phase 1
14    5 Bedroom House for sale in B Block Sushant Lo...
15    6 Bedroom House for sale in New Palam Vihar Ph...
16              9 Bedroom House for sale in DLF Phase 2
17        7 Bedroom House for sale in Sector 38 Gurgaon
18          4 Bedroom House for sale in Nirvana Country
19          6 Bedroom House for sale in Uppals Southend
20         9 Bedroom House for sale in Sector 9 Gurgaon
21        5 Bedroom House for sale in Sector 66 Gurgaon
22        4 Bedroom House for sale in Sector 48 Gurgaon
23        4 Bedroom House for sale in Sector 48 Gurgaon
24              9 Bedroom House for sale in DLF Phase 2
25      5 Bedroom House for sale in Sushant Lok Phase 1
26         5 Bedroom House for sale in Sector 4 Gurgaon
27         9 Bedroom House for sale in Sector 9 Gurgaon
28        9 Bedroom House for sale in Sector 40 Gurgaon
29          5 Bedroom House for sale in Nirvana Country
30        4 Bedroom House for sale in Sector 67 Gurgaon
31              5 Bedroom House for sale in DLF Phase 2
32             10 Bedroom House for sale in DLF Phase 2
33    4 Bedroom House for sale in Hsiidc Plot Sector...
34         2 Bedroom House for sale in Sector 7 Gurgaon
35      4 Bedroom House for sale in Sushant Lok Phase 3
36             12 Bedroom House for sale in DLF Phase 2
37         3 Bedroom House for sale in Sector 15 Part 2
38        4 Bedroom House for sale in Sector 28 Gurgaon
39              5 Bedroom House for sale in DLF Phase 2
40              5 Bedroom House for sale in DLF Phase 1
41              2 Bedroom House for sale in Narsinghpur
42       12 Bedroom House for sale in Sector 55 Gurgaon
43     16 Bedroom House for sale in Sushant Lok Phase 1
44       12 Bedroom House for sale in Sector 56 Gurgaon
45       16 Bedroom House for sale in Sector 56 Gurgaon
46              5 Bedroom House for sale in DLF Phase 2
47        5 Bedroom House for sale in Sector 66 Gurgaon
48       4 Bedroom House for sale in Sector 70A Gurgaon
49    4 Bedroom House for sale in C Block Sushant Lo...
50              3 Bedroom House for sale in Palam Vihar
51              8 Bedroom House for sale in Palam Vihar
52           5 Bedroom House for sale in Greenwood City
53       4 Bedroom House for sale in Sector 112 Gurgaon
54          6 Bedroom House for sale in Uppals Southend
55        3 Bedroom House for sale in Sector 48 Gurgaon
56        4 Bedroom House for sale in Sector 48 Gurgaon
57        4 Bedroom House for sale in Sector 55 Gurgaon
58        4 Bedroom House for sale in Sector 91 Gurgaon
59        4 Bedroom House for sale in Sector 86 Gurgaon
60        4 Bedroom House for sale in Sector 86 Gurgaon
61    8 Bedroom House for sale in B1 Block Sector 57...
62              6 Bedroom House for sale in DLF Phase 1
63      6 Bedroom House for sale in Sushant Lok Phase 3
64      6 Bedroom House for sale in Sushant Lok Phase 3
65              4 Bedroom House for sale in DLF Phase 4
66          8 Bedroom House for sale in Uppals Southend
67          6 Bedroom House for sale in Uppals Southend
68        4 Bedroom House for sale in Sector 48 Gurgaon
69              4 Bedroom House for sale in Malibu Town
70        5 Bedroom House for sale in Sector 33 Gurgaon
71              5 Bedroom House for sale in DLF Phase 1
72             3 Bedroom House for sale in South City 1
73       5 Bedroom House for sale in Sector 111 Gurgaon
74        3 Bedroom House for sale in Sector 40 Gurgaon
75       5 Bedroom House for sale in Sector 109 Gurgaon
76       4 Bedroom House for sale in Sector 109 Gurgaon
77        5 Bedroom House for sale in Sector 14 Gurgaon
78    5 Bedroom House for sale in C Block Sushant Lo...
79        5 Bedroom House for sale in Sector 66 Gurgaon
80        4 Bedroom House for sale in Sector 66 Gurgaon
81       5 Bedroom House for sale in Sector 109 Gurgaon
82       4 Bedroom House for sale in Sector 109 Gurgaon
83       3 Bedroom House for sale in Sector 109 Gurgaon
84       4 Bedroom House for sale in Sector 112 Gurgaon
85        4 Bedroom House for sale in Sector 66 Gurgaon
86        5 Bedroom House for sale in Sector 66 Gurgaon
87        4 Bedroom House for sale in Sector 66 Gurgaon
88        3 Bedroom House for sale in Sector 73 Gurgaon
89       5 Bedroom House for sale in Sector 109 Gurgaon
90       4 Bedroom House for sale in Sector 109 Gurgaon
91       3 Bedroom House for sale in Sector 109 Gurgaon
92       12 Bedroom House for sale in Sector 40 Gurgaon
93        4 Bedroom House for sale in Sector 23 Gurgaon
94        5 Bedroom House for sale in Sector 66 Gurgaon
95        4 Bedroom House for sale in Sector 66 Gurgaon
96       4 Bedroom House for sale in Sector 109 Gurgaon
97       3 Bedroom House for sale in Sector 109 Gurgaon
98        4 Bedroom House for sale in Sector 23 Gurgaon
99        4 Bedroom House for sale in Sector 72 Gurgaon
100      4 Bedroom House for sale in Sector 112 Gurgaon
101      5 Bedroom House for sale in Sector 63A Gurgaon
102      3 Bedroom House for sale in Sector 63A Gurgaon
103      4 Bedroom House for sale in Sector 109 Gurgaon
104      4 Bedroom House for sale in Sector 109 Gurgaon
105       4 Bedroom House for sale in Sector 48 Gurgaon
106       3 Bedroom House for sale in Sector 48 Gurgaon
107       5 Bedroom House for sale in Sector 48 Gurgaon
108       4 Bedroom House for sale in Sector 48 Gurgaon
109       3 Bedroom House for sale in Sector 48 Gurgaon
110       3 Bedroom House for sale in Sector 73 Gurgaon
111       5 Bedroom House for sale in Sector 48 Gurgaon
112       4 Bedroom House for sale in Sector 48 Gurgaon
113       3 Bedroom House for sale in Sector 48 Gurgaon
114       4 Bedroom House for sale in Sector 66 Gurgaon
115       5 Bedroom House for sale in Sector 66 Gurgaon
116       4 Bedroom House for sale in Sector 66 Gurgaon
117       4 Bedroom House for sale in Sector 65 Gurgaon
118         4 Bedroom House for sale in Sector-33 Sohna
119        3 Bedroom House for sale in Sector 4 Gurgaon
120        3 Bedroom House for sale in Sector 4 Gurgaon
121         4 Bedroom House for sale in Nirvana Country
122       5 Bedroom House for sale in Sector 48 Gurgaon
123      5 Bedroom House for sale in Sector 111 Gurgaon
124      5 Bedroom House for sale in Sector 111 Gurgaon
125       5 Bedroom House for sale in Sector 82 Gurgaon
126    3 Bedroom House for sale in Laxman Vihar Phase 2
127      4 Bedroom House for sale in Sector 109 Gurgaon
128       3 Bedroom House for sale in Sector 73 Gurgaon
129      4 Bedroom House for sale in Sector 109 Gurgaon
130        3 Bedroom House for sale in Sector 9 Gurgaon
131      12 Bedroom House for sale in Sector 56 Gurgaon
132       4 Bedroom House for sale in Sector 48 Gurgaon
133       4 Bedroom House for sale in Sector 82 Gurgaon
134              2 Bedroom House for sale in New Colony
135        4 Bedroom House for sale in Sector 7 Gurgaon
136        2 Bedroom House for sale in Sector 7 Gurgaon
137        3 Bedroom House for sale in Sector 7 Gurgaon
138        3 Bedroom House for sale in Sector 7 Gurgaon
139         4 Bedroom House for sale in Nirvana Country
140       4 Bedroom House for sale in Sector 48 Gurgaon
141       4 Bedroom House for sale in Sector 66 Gurgaon
142      5 Bedroom House for sale in Sector 109 Gurgaon
143      4 Bedroom House for sale in Sector 109 Gurgaon
144      7 Bedroom House for sale in Sector 109 Gurgaon
145      5 Bedroom House for sale in Sector 109 Gurgaon
146      5 Bedroom House for sale in Sector 109 Gurgaon
147       5 Bedroom House for sale in Sector 56 Gurgaon
148      5 Bedroom House for sale in Sector 17C Gurgaon
149      4 Bedroom House for sale in Sector 109 Gurgaon
150      4 Bedroom House for sale in Sector 109 Gurgaon
151      4 Bedroom House for sale in Sector 70A Gurgaon
152      4 Bedroom House for sale in Sector 70A Gurgaon
153             6 Bedroom House for sale in DLF Phase 2
154      4 Bedroom House for sale in Sector 109 Gurgaon
155      5 Bedroom House for sale in Sector 109 Gurgaon
156           3 Bedroom House for sale in Rajendra Park
157    3 Bedroom House for sale in Laxman Vihar Phase 2
158    3 Bedroom House for sale in Laxman Vihar Phase 2
159    2 Bedroom House for sale in Laxman Vihar Phase 2
160    1 Bedroom House for sale in Laxman Vihar Phase 2
161    2 Bedroom House for sale in Laxman Vihar Phase 2
162    3 Bedroom House for sale in Laxman Vihar Phase 2
163     6 Bedroom House for sale in Sushant Lok Phase 1
164      4 Bedroom House for sale in Sector 109 Gurgaon
165       9 Bedroom House for sale in Sector 57 Gurgaon
166      18 Bedroom House for sale in Sector 55 Gurgaon
167          16 Bedroom House for sale in Shivaji Nagar
168       4 Bedroom House for sale in Sector 31 Gurgaon
169     7 Bedroom House for sale in Sushant Lok Phase 1
170     1 Bedroom House for sale in Sushant Lok Phase 1
171         4 Bedroom House for sale in Nirvana Country
172         3 Bedroom House for sale in Nirvana Country
173             5 Bedroom House for sale in Palam Vihar
174      7 Bedroom House for sale in Sector 109 Gurgaon
175      7 Bedroom House for sale in Sector 109 Gurgaon
176      4 Bedroom House for sale in Sector 70A Gurgaon
177      4 Bedroom House for sale in Sector 109 Gurgaon
178         4 Bedroom House for sale in Nirvana Country
179       5 Bedroom House for sale in Sector 63 Gurgaon
180       4 Bedroom House for sale in Sector 81 Gurgaon
181      12 Bedroom House for sale in Sector 56 Gurgaon
182            2 Bedroom House for sale in Laxman Vihar
183                 4 Bedroom House for sale in Ghamroj
184   8 Bedroom House for sale in Palam Vihar Extension
185       1 Bedroom House for sale in Sector 57 Gurgaon
186        3 Bedroom House for sale in Sector 8 Gurgaon
187             5 Bedroom House for sale in Patel Nagar
188             6 Bedroom House for sale in Patel Nagar
189           12 Bedroom House for sale in Pratap Nagar
190           12 Bedroom House for sale in South City 1
191       5 Bedroom House for sale in Sector 23 Gurgaon
192             8 Bedroom House for sale in DLF Phase 3
193             7 Bedroom House for sale in DLF Phase 4
194             5 Bedroom House for sale in Maruti Kunj
195             5 Bedroom House for sale in Rajiv Chowk
196            3 Bedroom House for sale in Laxman Vihar
197               4 Bedroom House for sale in Madanpuri
198       7 Bedroom House for sale in Sector 11 Gurgaon
199           5 Bedroom House for sale in Shivaji Nagar
200           9 Bedroom House for sale in Dharam Colony
201          3 Bedroom House for sale in Krishna Colony
202            3 Bedroom House for sale in Laxman Vihar
203             3 Bedroom House for sale in DLF Phase 3
204   4 Bedroom House for sale in Ashok Vihar Phase ...
205       9 Bedroom House for sale in Sector 9A Gurgaon
206        3 Bedroom House for sale in Sector 3 Gurgaon
207              3 Bedroom House for sale in Hira Nagar
208   4 Bedroom House for sale in Gopal Nagar, Garhi...
209   5 Bedroom House for sale in Jat Colony,Fazilpu...
210            7 Bedroom House for sale in South City 1
211     19 Bedroom House for sale in Sector 17A Gurgaon
212       4 Bedroom House for sale in Sector 56 Gurgaon
213                   2 Bedroom House for sale in Kheri
214               6 Bedroom House for sale in Madanpuri
215             7 Bedroom House for sale in DLF Phase 3
216              5 Bedroom House for sale in Sohna Road
217         3 Bedroom House for sale in Dayanand Colony
218             2 Bedroom House for sale in Mohan Nagar
219           3 Bedroom House for sale in Rajendra Park
220              2 Bedroom House for sale in Daulatabad
221   5 Bedroom House for sale in Ashok Vihar Phase ...
222           2 Bedroom House for sale in Vishnu Garden
223             4 Bedroom House for sale in DLF Phase 1
224               8 Bedroom House for sale in New Basti
225           4 Bedroom House for sale in Shivaji Nagar
226                 8 Bedroom House for sale in Manesar
227              4 Bedroom House for sale in New Colony
228        4 Bedroom House for sale in Sector 8 Gurgaon
229             3 Bedroom House for sale in Ashok Vihar
230             4 Bedroom House for sale in Maruti Kunj
231            5 Bedroom House for sale in Laxmi Garden
232             4 Bedroom House for sale in Mohan Nagar
233       1 Bedroom House for sale in Sector 9B Gurgaon
234         6 Bedroom House for sale in Saraswati Vihar
235             8 Bedroom House for sale in IMT Manesar
236             2 Bedroom House for sale in Bhora Kalan
237      9 Bedroom House for sale in near nand hospital
238             8 Bedroom House for sale in DLF Phase 1
239               10 Bedroom House for sale in Shivpuri
240       4 Bedroom House for sale in Sector 92 Gurgaon
241       4 Bedroom House for sale in Sector 76 Gurgaon
242       5 Bedroom House for sale in Sector 72 Gurgaon
243              5 Bedroom House for sale in Jyoti Park
244                   3 Bedroom House for sale in Sohna
245           4 Bedroom House for sale in Subhash Nagar
246         2 Bedroom House for sale in New Palam Vihar
247             6 Bedroom House for sale in Palam Vihar
248     2 Bedroom House for sale in Surat Nagar Phase 2
249       3 Bedroom House for sale in Sector 14 Gurgaon
250       5 Bedroom House for sale in Sector 33 Gurgaon
251       8 Bedroom House for sale in Sector 56 Gurgaon
252             3 Bedroom House for sale in Ashok Vihar
253       3 Bedroom House for sale in Sector 93 Gurgaon
254        5 Bedroom House for sale in Sector 5 Gurgaon
255           4 Bedroom House for sale in Rajendra Park
256            10 Bedroom House for sale in Rajiv Nagar
257               5 Bedroom House for sale in Madanpuri
258   3 Bedroom House for sale in New Palam Vihar Ph...
259             6 Bedroom House for sale in Arjun Nagar
260     4 Bedroom House for sale in Ashok Vihar Phase I
261        2 Bedroom House for sale in Sector 5 Gurgaon
262             5 Bedroom House for sale in Surya Vihar
263   6 Bedroom House for sale in Block H Ashok Viha...
264             5 Bedroom House for sale in DLF Phase 1
265          3 Bedroom House for sale in Devilal Colony
266      10 Bedroom House for sale in Sector 38 Gurgaon
267             3 Bedroom House for sale in Surya Vihar
268              6 Bedroom House for sale in Prem Nagar
269              6 Bedroom House for sale in Bhim Nagar
270    2 Bedroom House for sale in Laxman Vihar Phase 2
271             7 Bedroom House for sale in Surat Nagar
272            5 Bedroom House for sale in Gandhi Nagar
273                 5 Bedroom House for sale in Khandsa
274      3 Bedroom House for sale in Sector 109 Gurgaon
275   1 Bedroom House for sale in Ashok Vihar Phase ...
276              5 Bedroom House for sale in Ravi Nagar
277             3 Bedroom House for sale in Maruti Kunj
278           7 Bedroom House for sale in Rajendra Park
279       5 Bedroom House for sale in Sector 50 Gurgaon
280   4 Bedroom House for sale in URBAN ESTATE, SECT...
281   3 Bedroom House for sale in New Palam Vihar Ph...
282       36 Bedroom House for sale in West Rajiv Nagar
283   2 Bedroom House for sale in Ashok Vihar Phase ...
284     6 Bedroom House for sale in Surat Nagar Phase 2
285       6 Bedroom House for sale in Sector 11 Gurgaon
286           5 Bedroom House for sale in Vishnu Garden
287     3 Bedroom House for sale in Sushant Lok Phase 3
288       4 Bedroom House for sale in Near Khandsa Road
289          2 Bedroom House for sale in Devilal Colony
290          9 Bedroom House for sale in Sheetla Colony
291            5 Bedroom House for sale in Laxman Vihar
292             6 Bedroom House for sale in Farukhnagar
293             10 Bedroom House for sale in Ravi Nagar
294         1 Bedroom House for sale in Mianwali Colony
295        2 Bedroom House for sale in Sector 8 Gurgaon
296           3 Bedroom House for sale in Dharam Colony
297             4 Bedroom House for sale in Palam Vihar
298       4 Bedroom House for sale in Sector 55 Gurgaon
299   4 Bedroom House for sale in Part 3 Sector 5 Gu...
300                   1 Bedroom House for sale in Sohna
301       3 Bedroom House for sale in Sector 38 Gurgaon
302         4 Bedroom House for sale in Saraswati Vihar
303       4 Bedroom House for sale in Sector 63 Gurgaon
304                 7 Bedroom House for sale in Lucknow
305            4 Bedroom House for sale in Pataudi Road
306             8 Bedroom House for sale in Surya Vihar
307              4 Bedroom House for sale in Ravi Nagar
308       5 Bedroom House for sale in Sector 81 Gurgaon
309           9 Bedroom House for sale in Subhash Nagar
310       3 Bedroom House for sale in Sector 38 Gurgaon
311       2 Bedroom House for sale in Sector 56 Gurgaon
312         4 Bedroom House for sale in Sector-33 Sohna
313       6 Bedroom House for sale in Sector 70 Gurgaon
314      3 Bedroom House for sale in Sector 105 Gurgaon
315              5 Bedroom House for sale in Jyoti Park
316             6 Bedroom House for sale in DLF Phase 2
317            12 Bedroom House for sale in Malibu Town
318       5 Bedroom House for sale in Sector 28 Gurgaon
319       3 Bedroom House for sale in Sector 66 Gurgaon
320   9 Bedroom House for sale in C Block Sushant Lo...
321              5 Bedroom House for sale in Bhim Nagar
322              4 Bedroom House for sale in Jyoti Park
323         6 Bedroom House for sale in Nirvana Country
324       9 Bedroom House for sale in Sector 12 Gurgaon
325            5 Bedroom House for sale in Laxman Vihar
326            3 Bedroom House for sale in Laxman Vihar
327      5 Bedroom House for sale in Sector 109 Gurgaon
328      4 Bedroom House for sale in Sector 109 Gurgaon
329      5 Bedroom House for sale in Sector 109 Gurgaon
330      4 Bedroom House for sale in Sector 109 Gurgaon
331      3 Bedroom House for sale in Sector 109 Gurgaon
332            4 Bedroom House for sale in Laxman Vihar
333            6 Bedroom House for sale in Laxman Vihar
334            2 Bedroom House for sale in Shakti Nagar
335      5 Bedroom House for sale in Sector 37D Gurgaon
336            2 Bedroom House for sale in Baldev Nagar
337                2 Bedroom House for sale in Shivpuri
338               4 Bedroom House for sale in New Basti
339      10 Bedroom House for sale in Sector 56 Gurgaon
340             1 Bedroom House for sale in Rajiv Nagar
341           2 Bedroom House for sale in Vishnu Garden
342            6 Bedroom House for sale in Acharya Puri
343                10 Bedroom House for sale in Bhondsi
344      2 Bedroom House for sale in Sector 105 Gurgaon
345             3 Bedroom House for sale in Arjun Nagar
346             3 Bedroom House for sale in DLF Phase 2
347       4 Bedroom House for sale in Sector 92 Gurgaon
348      4 Bedroom House for sale in Sector 108 Gurgaon
349   2 Bedroom House for sale in Ashok Vihar Phase ...
350   6 Bedroom House for sale in Ashok Vihar Phase ...
351      3 Bedroom House for sale in Sector 109 Gurgaon
352           2 Bedroom House for sale in Garhi Harsaru
353             3 Bedroom House for sale in Arjun Nagar
354   2 Bedroom House for sale in Palam Vihar Extension
355             2 Bedroom House for sale in Rajiv Nagar

In [21]:
l=list(range(60,73))
h.drop(index=l,axis=0,inplace=True)

In [22]:
h

                                          property_name  \
0        5 Bedroom House for sale in Sector 70A Gurgaon
1      5 Bedroom House for sale in Sector 21A Faridabad
2      10 Bedroom House for sale in Sushant Lok Phase 1
3        21 Bedroom House for sale in Sector 54 Gurgaon
4      12 Bedroom House for sale in Sushant Lok Phase 1
5      20 Bedroom House for sale in Sushant Lok Phase 1
6         5 Bedroom House for sale in Sector 66 Gurgaon
7              16 Bedroom House for sale in DLF Phase 1
8               6 Bedroom House for sale in DLF Phase 2
9       3 Bedroom House for sale in Sushant Lok Phase 1
10              4 Bedroom House for sale in DLF Phase 2
11              6 Bedroom House for sale in DLF Phase 4
12             13 Bedroom House for sale in DLF Phase 3
13              5 Bedroom House for sale in DLF Phase 1
14    5 Bedroom House for sale in B Block Sushant Lo...
15    6 Bedroom House for sale in New Palam Vihar Ph...
16              9 Bedroom House for sale in DLF Phase 2
17        7 Bedroom House for sale in Sector 38 Gurgaon
18          4 Bedroom House for sale in Nirvana Country
19          6 Bedroom House for sale in Uppals Southend
20         9 Bedroom House for sale in Sector 9 Gurgaon
21        5 Bedroom House for sale in Sector 66 Gurgaon
22        4 Bedroom House for sale in Sector 48 Gurgaon
23        4 Bedroom House for sale in Sector 48 Gurgaon
24              9 Bedroom House for sale in DLF Phase 2
25      5 Bedroom House for sale in Sushant Lok Phase 1
26         5 Bedroom House for sale in Sector 4 Gurgaon
27         9 Bedroom House for sale in Sector 9 Gurgaon
28        9 Bedroom House for sale in Sector 40 Gurgaon
29          5 Bedroom House for sale in Nirvana Country
30        4 Bedroom House for sale in Sector 67 Gurgaon
31              5 Bedroom House for sale in DLF Phase 2
32             10 Bedroom House for sale in DLF Phase 2
33    4 Bedroom House for sale in Hsiidc Plot Sector...
34         2 Bedroom House for sale in Sector 7 Gurgaon
35      4 Bedroom House for sale in Sushant Lok Phase 3
36             12 Bedroom House for sale in DLF Phase 2
37         3 Bedroom House for sale in Sector 15 Part 2
38        4 Bedroom House for sale in Sector 28 Gurgaon
39              5 Bedroom House for sale in DLF Phase 2
40              5 Bedroom House for sale in DLF Phase 1
41              2 Bedroom House for sale in Narsinghpur
42       12 Bedroom House for sale in Sector 55 Gurgaon
43     16 Bedroom House for sale in Sushant Lok Phase 1
44       12 Bedroom House for sale in Sector 56 Gurgaon
45       16 Bedroom House for sale in Sector 56 Gurgaon
46              5 Bedroom House for sale in DLF Phase 2
47        5 Bedroom House for sale in Sector 66 Gurgaon
48       4 Bedroom House for sale in Sector 70A Gurgaon
49    4 Bedroom House for sale in C Block Sushant Lo...
50              3 Bedroom House for sale in Palam Vihar
51              8 Bedroom House for sale in Palam Vihar
52           5 Bedroom House for sale in Greenwood City
53       4 Bedroom House for sale in Sector 112 Gurgaon
54          6 Bedroom House for sale in Uppals Southend
55        3 Bedroom House for sale in Sector 48 Gurgaon
56        4 Bedroom House for sale in Sector 48 Gurgaon
57        4 Bedroom House for sale in Sector 55 Gurgaon
58        4 Bedroom House for sale in Sector 91 Gurgaon
59        4 Bedroom House for sale in Sector 86 Gurgaon
73       5 Bedroom House for sale in Sector 111 Gurgaon
74        3 Bedroom House for sale in Sector 40 Gurgaon
75       5 Bedroom House for sale in Sector 109 Gurgaon
76       4 Bedroom House for sale in Sector 109 Gurgaon
77        5 Bedroom House for sale in Sector 14 Gurgaon
78    5 Bedroom House for sale in C Block Sushant Lo...
79        5 Bedroom House for sale in Sector 66 Gurgaon
80        4 Bedroom House for sale in Sector 66 Gurgaon
81       5 Bedroom House for sale in Sector 109 Gurgaon
82       4 Bedroom House for sale in Sector 109 Gurgaon
83       3 Bedroom House for sale in Sector 109 Gurgaon
84       4 Bedroom House for sale in Sector 112 Gurgaon
85        4 Bedroom House for sale in Sector 66 Gurgaon
86        5 Bedroom House for sale in Sector 66 Gurgaon
87        4 Bedroom House for sale in Sector 66 Gurgaon
88        3 Bedroom House for sale in Sector 73 Gurgaon
89       5 Bedroom House for sale in Sector 109 Gurgaon
90       4 Bedroom House for sale in Sector 109 Gurgaon
91       3 Bedroom House for sale in Sector 109 Gurgaon
92       12 Bedroom House for sale in Sector 40 Gurgaon
93        4 Bedroom House for sale in Sector 23 Gurgaon
94        5 Bedroom House for sale in Sector 66 Gurgaon
95        4 Bedroom House for sale in Sector 66 Gurgaon
96       4 Bedroom House for sale in Sector 109 Gurgaon
97       3 Bedroom House for sale in Sector 109 Gurgaon
98        4 Bedroom House for sale in Sector 23 Gurgaon
99        4 Bedroom House for sale in Sector 72 Gurgaon
100      4 Bedroom House for sale in Sector 112 Gurgaon
101      5 Bedroom House for sale in Sector 63A Gurgaon
102      3 Bedroom House for sale in Sector 63A Gurgaon
103      4 Bedroom House for sale in Sector 109 Gurgaon
104      4 Bedroom House for sale in Sector 109 Gurgaon
105       4 Bedroom House for sale in Sector 48 Gurgaon
106       3 Bedroom House for sale in Sector 48 Gurgaon
107       5 Bedroom House for sale in Sector 48 Gurgaon
108       4 Bedroom House for sale in Sector 48 Gurgaon
109       3 Bedroom House for sale in Sector 48 Gurgaon
110       3 Bedroom House for sale in Sector 73 Gurgaon
111       5 Bedroom House for sale in Sector 48 Gurgaon
112       4 Bedroom House for sale in Sector 48 Gurgaon
113       3 Bedroom House for sale in Sector 48 Gurgaon
114       4 Bedroom House for sale in Sector 66 Gurgaon
115       5 Bedroom House for sale in Sector 66 Gurgaon
116       4 Bedroom House for sale in Sector 66 Gurgaon
117       4 Bedroom House for sale in Sector 65 Gurgaon
118         4 Bedroom House for sale in Sector-33 Sohna
119        3 Bedroom House for sale in Sector 4 Gurgaon
120        3 Bedroom House for sale in Sector 4 Gurgaon
121         4 Bedroom House for sale in Nirvana Country
122       5 Bedroom House for sale in Sector 48 Gurgaon
123      5 Bedroom House for sale in Sector 111 Gurgaon
124      5 Bedroom House for sale in Sector 111 Gurgaon
125       5 Bedroom House for sale in Sector 82 Gurgaon
126    3 Bedroom House for sale in Laxman Vihar Phase 2
127      4 Bedroom House for sale in Sector 109 Gurgaon
128       3 Bedroom House for sale in Sector 73 Gurgaon
129      4 Bedroom House for sale in Sector 109 Gurgaon
130        3 Bedroom House for sale in Sector 9 Gurgaon
131      12 Bedroom House for sale in Sector 56 Gurgaon
132       4 Bedroom House for sale in Sector 48 Gurgaon
133       4 Bedroom House for sale in Sector 82 Gurgaon
134              2 Bedroom House for sale in New Colony
135        4 Bedroom House for sale in Sector 7 Gurgaon
136        2 Bedroom House for sale in Sector 7 Gurgaon
137        3 Bedroom House for sale in Sector 7 Gurgaon
138        3 Bedroom House for sale in Sector 7 Gurgaon
139         4 Bedroom House for sale in Nirvana Country
140       4 Bedroom House for sale in Sector 48 Gurgaon
141       4 Bedroom House for sale in Sector 66 Gurgaon
142      5 Bedroom House for sale in Sector 109 Gurgaon
143      4 Bedroom House for sale in Sector 109 Gurgaon
144      7 Bedroom House for sale in Sector 109 Gurgaon
145      5 Bedroom House for sale in Sector 109 Gurgaon
146      5 Bedroom House for sale in Sector 109 Gurgaon
147       5 Bedroom House for sale in Sector 56 Gurgaon
148      5 Bedroom House for sale in Sector 17C Gurgaon
149      4 Bedroom House for sale in Sector 109 Gurgaon
150      4 Bedroom House for sale in Sector 109 Gurgaon
151      4 Bedroom House for sale in Sector 70A Gurgaon
152      4 Bedroom House for sale in Sector 70A Gurgaon
153             6 Bedroom House for sale in DLF Phase 2
154      4 Bedroom House for sale in Sector 109 Gurgaon
155      5 Bedroom House for sale in Sector 109 Gurgaon
156           3 Bedroom House for sale in Rajendra Park
157    3 Bedroom House for sale in Laxman Vihar Phase 2
158    3 Bedroom House for sale in Laxman Vihar Phase 2
159    2 Bedroom House for sale in Laxman Vihar Phase 2
160    1 Bedroom House for sale in Laxman Vihar Phase 2
161    2 Bedroom House for sale in Laxman Vihar Phase 2
162    3 Bedroom House for sale in Laxman Vihar Phase 2
163     6 Bedroom House for sale in Sushant Lok Phase 1
164      4 Bedroom House for sale in Sector 109 Gurgaon
165       9 Bedroom House for sale in Sector 57 Gurgaon
166      18 Bedroom House for sale in Sector 55 Gurgaon
167          16 Bedroom House for sale in Shivaji Nagar
168       4 Bedroom House for sale in Sector 31 Gurgaon
169     7 Bedroom House for sale in Sushant Lok Phase 1
170     1 Bedroom House for sale in Sushant Lok Phase 1
171         4 Bedroom House for sale in Nirvana Country
172         3 Bedroom House for sale in Nirvana Country
173             5 Bedroom House for sale in Palam Vihar
174      7 Bedroom House for sale in Sector 109 Gurgaon
175      7 Bedroom House for sale in Sector 109 Gurgaon
176      4 Bedroom House for sale in Sector 70A Gurgaon
177      4 Bedroom House for sale in Sector 109 Gurgaon
178         4 Bedroom House for sale in Nirvana Country
179       5 Bedroom House for sale in Sector 63 Gurgaon
180       4 Bedroom House for sale in Sector 81 Gurgaon
181      12 Bedroom House for sale in Sector 56 Gurgaon
182            2 Bedroom House for sale in Laxman Vihar
183                 4 Bedroom House for sale in Ghamroj
184   8 Bedroom House for sale in Palam Vihar Extension
185       1 Bedroom House for sale in Sector 57 Gurgaon
186        3 Bedroom House for sale in Sector 8 Gurgaon
187             5 Bedroom House for sale in Patel Nagar
188             6 Bedroom House for sale in Patel Nagar
189           12 Bedroom House for sale in Pratap Nagar
190           12 Bedroom House for sale in South City 1
191       5 Bedroom House for sale in Sector 23 Gurgaon
192             8 Bedroom House for sale in DLF Phase 3
193             7 Bedroom House for sale in DLF Phase 4
194             5 Bedroom House for sale in Maruti Kunj
195             5 Bedroom House for sale in Rajiv Chowk
196            3 Bedroom House for sale in Laxman Vihar
197               4 Bedroom House for sale in Madanpuri
198       7 Bedroom House for sale in Sector 11 Gurgaon
199           5 Bedroom House for sale in Shivaji Nagar
200           9 Bedroom House for sale in Dharam Colony
201          3 Bedroom House for sale in Krishna Colony
202            3 Bedroom House for sale in Laxman Vihar
203             3 Bedroom House for sale in DLF Phase 3
204   4 Bedroom House for sale in Ashok Vihar Phase ...
205       9 Bedroom House for sale in Sector 9A Gurgaon
206        3 Bedroom House for sale in Sector 3 Gurgaon
207              3 Bedroom House for sale in Hira Nagar
208   4 Bedroom House for sale in Gopal Nagar, Garhi...
209   5 Bedroom House for sale in Jat Colony,Fazilpu...
210            7 Bedroom House for sale in South City 1
211     19 Bedroom House for sale in Sector 17A Gurgaon
212       4 Bedroom House for sale in Sector 56 Gurgaon
213                   2 Bedroom House for sale in Kheri
214               6 Bedroom House for sale in Madanpuri
215             7 Bedroom House for sale in DLF Phase 3
216              5 Bedroom House for sale in Sohna Road
217         3 Bedroom House for sale in Dayanand Colony
218             2 Bedroom House for sale in Mohan Nagar
219           3 Bedroom House for sale in Rajendra Park
220              2 Bedroom House for sale in Daulatabad
221   5 Bedroom House for sale in Ashok Vihar Phase ...
222           2 Bedroom House for sale in Vishnu Garden
223             4 Bedroom House for sale in DLF Phase 1
224               8 Bedroom House for sale in New Basti
225           4 Bedroom House for sale in Shivaji Nagar
226                 8 Bedroom House for sale in Manesar
227              4 Bedroom House for sale in New Colony
228        4 Bedroom House for sale in Sector 8 Gurgaon
229             3 Bedroom House for sale in Ashok Vihar
230             4 Bedroom House for sale in Maruti Kunj
231            5 Bedroom House for sale in Laxmi Garden
232             4 Bedroom House for sale in Mohan Nagar
233       1 Bedroom House for sale in Sector 9B Gurgaon
234         6 Bedroom House for sale in Saraswati Vihar
235             8 Bedroom House for sale in IMT Manesar
236             2 Bedroom House for sale in Bhora Kalan
237      9 Bedroom House for sale in near nand hospital
238             8 Bedroom House for sale in DLF Phase 1
239               10 Bedroom House for sale in Shivpuri
240       4 Bedroom House for sale in Sector 92 Gurgaon
241       4 Bedroom House for sale in Sector 76 Gurgaon
242       5 Bedroom House for sale in Sector 72 Gurgaon
243              5 Bedroom House for sale in Jyoti Park
244                   3 Bedroom House for sale in Sohna
245           4 Bedroom House for sale in Subhash Nagar
246         2 Bedroom House for sale in New Palam Vihar
247             6 Bedroom House for sale in Palam Vihar
248     2 Bedroom House for sale in Surat Nagar Phase 2
249       3 Bedroom House for sale in Sector 14 Gurgaon
250       5 Bedroom House for sale in Sector 33 Gurgaon
251       8 Bedroom House for sale in Sector 56 Gurgaon
252             3 Bedroom House for sale in Ashok Vihar
253       3 Bedroom House for sale in Sector 93 Gurgaon
254        5 Bedroom House for sale in Sector 5 Gurgaon
255           4 Bedroom House for sale in Rajendra Park
256            10 Bedroom House for sale in Rajiv Nagar
257               5 Bedroom House for sale in Madanpuri
258   3 Bedroom House for sale in New Palam Vihar Ph...
259             6 Bedroom House for sale in Arjun Nagar
260     4 Bedroom House for sale in Ashok Vihar Phase I
261        2 Bedroom House for sale in Sector 5 Gurgaon
262             5 Bedroom House for sale in Surya Vihar
263   6 Bedroom House for sale in Block H Ashok Viha...
264             5 Bedroom House for sale in DLF Phase 1
265          3 Bedroom House for sale in Devilal Colony
266      10 Bedroom House for sale in Sector 38 Gurgaon
267             3 Bedroom House for sale in Surya Vihar
268              6 Bedroom House for sale in Prem Nagar
269              6 Bedroom House for sale in Bhim Nagar
270    2 Bedroom House for sale in Laxman Vihar Phase 2
271             7 Bedroom House for sale in Surat Nagar
272            5 Bedroom House for sale in Gandhi Nagar
273                 5 Bedroom House for sale in Khandsa
274      3 Bedroom House for sale in Sector 109 Gurgaon
275   1 Bedroom House for sale in Ashok Vihar Phase ...
276              5 Bedroom House for sale in Ravi Nagar
277             3 Bedroom House for sale in Maruti Kunj
278           7 Bedroom House for sale in Rajendra Park
279       5 Bedroom House for sale in Sector 50 Gurgaon
280   4 Bedroom House for sale in URBAN ESTATE, SECT...
281   3 Bedroom House for sale in New Palam Vihar Ph...
282       36 Bedroom House for sale in West Rajiv Nagar
283   2 Bedroom House for sale in Ashok Vihar Phase ...
284     6 Bedroom House for sale in Surat Nagar Phase 2
285       6 Bedroom House for sale in Sector 11 Gurgaon
286           5 Bedroom House for sale in Vishnu Garden
287     3 Bedroom House for sale in Sushant Lok Phase 3
288       4 Bedroom House for sale in Near Khandsa Road
289          2 Bedroom House for sale in Devilal Colony
290          9 Bedroom House for sale in Sheetla Colony
291            5 Bedroom House for sale in Laxman Vihar
292             6 Bedroom House for sale in Farukhnagar
293             10 Bedroom House for sale in Ravi Nagar
294         1 Bedroom House for sale in Mianwali Colony
295        2 Bedroom House for sale in Sector 8 Gurgaon
296           3 Bedroom House for sale in Dharam Colony
297             4 Bedroom House for sale in Palam Vihar
298       4 Bedroom House for sale in Sector 55 Gurgaon
299   4 Bedroom House for sale in Part 3 Sector 5 Gu...
300                   1 Bedroom House for sale in Sohna
301       3 Bedroom House for sale in Sector 38 Gurgaon
302         4 Bedroom House for sale in Saraswati Vihar
303       4 Bedroom House for sale in Sector 63 Gurgaon
304                 7 Bedroom House for sale in Lucknow
305            4 Bedroom House for sale in Pataudi Road
306             8 Bedroom House for sale in Surya Vihar
307              4 Bedroom House for sale in Ravi Nagar
308       5 Bedroom House for sale in Sector 81 Gurgaon
309           9 Bedroom House for sale in Subhash Nagar
310       3 Bedroom House for sale in Sector 38 Gurgaon
311       2 Bedroom House for sale in Sector 56 Gurgaon
312         4 Bedroom House for sale in Sector-33 Sohna
313       6 Bedroom House for sale in Sector 70 Gurgaon
314      3 Bedroom House for sale in Sector 105 Gurgaon
315              5 Bedroom House for sale in Jyoti Park
316             6 Bedroom House for sale in DLF Phase 2
317            12 Bedroom House for sale in Malibu Town
318       5 Bedroom House for sale in Sector 28 Gurgaon
319       3 Bedroom House for sale in Sector 66 Gurgaon
320   9 Bedroom House for sale in C Block Sushant Lo...
321              5 Bedroom House for sale in Bhim Nagar
322              4 Bedroom House for sale in Jyoti Park
323         6 Bedroom House for sale in Nirvana Country
324       9 Bedroom House for sale in Sector 12 Gurgaon
325            5 Bedroom House for sale in Laxman Vihar
326            3 Bedroom House for sale in Laxman Vihar
327      5 Bedroom House for sale in Sector 109 Gurgaon
328      4 Bedroom House for sale in Sector 109 Gurgaon
329      5 Bedroom House for sale in Sector 109 Gurgaon
330      4 Bedroom House for sale in Sector 109 Gurgaon
331      3 Bedroom House for sale in Sector 109 Gurgaon
332            4 Bedroom House for sale in Laxman Vihar
333            6 Bedroom House for sale in Laxman Vihar
334            2 Bedroom House for sale in Shakti Nagar
335      5 Bedroom House for sale in Sector 37D Gurgaon
336            2 Bedroom House for sale in Baldev Nagar
337                2 Bedroom House for sale in Shivpuri
338               4 Bedroom House for sale in New Basti
339      10 Bedroom House for sale in Sector 56 Gurgaon
340             1 Bedroom House for sale in Rajiv Nagar
341           2 Bedroom House for sale in Vishnu Garden
342            6 Bedroom House for sale in Acharya Puri
343                10 Bedroom House for sale in Bhondsi
344      2 Bedroom House for sale in Sector 105 Gurgaon
345             3 Bedroom House for sale in Arjun Nagar
346             3 Bedroom House for sale in DLF Phase 2
347       4 Bedroom House for sale in Sector 92 Gurgaon
348      4 Bedroom House for sale in Sector 108 Gurgaon
349   2 Bedroom House for sale in Ashok Vihar Phase ...
350   6 Bedroom House for sale in Ashok Vihar Phase ...
351      3 Bedroom House for sale in Sector 109 Gurgaon
352           2 Bedroom House for sale in Garhi Harsaru
353             3 Bedroom House for sale in Arjun Nagar
354   2 Bedroom House for sale in Palam Vihar Extension
355             2 Bedroom House for sale in Rajiv Nagar
356             7 Bedroom House for sale in Surya Vihar
357            4 Bedroom House for sale in Pratap Nagar
358            1 Bedroom House for sale in Baldev Nagar
359         2 Bedroom House for sale in New Palam Vihar
360           1 Bedroom House for sale in Subhash Nagar
361        4 Bedroom House for sale in Sector 1 Gurgaon
362   4 Bedroom House for sale in anand garden, sect...
363      4 Bedroom House for sale in Sector 10A Gurgaon
364       4 Bedroom House for sale in Sector 13 Gurgaon
365       3 Bedroom House for sale in Sector 31 Gurgaon
366                 2 Bedroom House for sale in Dhunela
367       7 Bedroom House for sale in Sector 3A Gurgaon
368            12 Bedroom House for sale in Heera Nagar

In [23]:
l=list(range(178,200)) 
h.drop(index=l,axis=0,inplace=True)

In [27]:
h['sector']=h['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip().str.lower()

In [28]:
h['sector']

0                                              sector 70a
1                                    sector 21a faridabad
2                                     sushant lok phase 1
3                                               sector 54
4                                     sushant lok phase 1
5                                     sushant lok phase 1
6                                               sector 66
7                                             dlf phase 1
8                                             dlf phase 2
9                                     sushant lok phase 1
10                                            dlf phase 2
11                                            dlf phase 4
12                                            dlf phase 3
13                                            dlf phase 1
14                            b block sushant lok phase 1
15                                new palam vihar phase 1
16                                            dlf phase 2
17                                              sector 38
18                                        nirvana country
19                                        uppals southend
20                                               sector 9
21                                              sector 66
22                                              sector 48
23                                              sector 48
24                                            dlf phase 2
25                                    sushant lok phase 1
26                                               sector 4
27                                               sector 9
28                                              sector 40
29                                        nirvana country
30                                              sector 67
31                                            dlf phase 2
32                                            dlf phase 2
33                       hsiidc plot sector 1 imt manesar
34                                               sector 7
35                                    sushant lok phase 3
36                                            dlf phase 2
37                                       sector 15 part 2
38                                              sector 28
39                                            dlf phase 2
40                                            dlf phase 1
41                                                   nars
42                                              sector 55
43                                    sushant lok phase 1
44                                              sector 56
45                                              sector 56
46                                            dlf phase 2
47                                              sector 66
48                                             sector 70a
49                            c block sushant lok phase 1
50                                            palam vihar
51                                            palam vihar
52                                         greenwood city
53                                             sector 112
54                                        uppals southend
55                                              sector 48
56                                              sector 48
57                                              sector 55
58                                              sector 91
59                                              sector 86
73                                             sector 111
74                                              sector 40
75                                             sector 109
76                                             sector 109
77                                              sector 14
78                            c block sushant lok phase 1
79                                              sector 66
80                                              sector 66
81                                             sector 109
82                                             sector 109
83                                             sector 109
84                                             sector 112
85                                              sector 66
86                                              sector 66
87                                              sector 66
88                                              sector 73
89                                             sector 109
90                                             sector 109
91                                             sector 109
92                                              sector 40
93                                              sector 23
94                                              sector 66
95                                              sector 66
96                                             sector 109
97                                             sector 109
98                                              sector 23
99                                              sector 72
100                                            sector 112
101                                            sector 63a
102                                            sector 63a
103                                            sector 109
104                                            sector 109
105                                             sector 48
106                                             sector 48
107                                             sector 48
108                                             sector 48
109                                             sector 48
110                                             sector 73
111                                             sector 48
112                                             sector 48
113                                             sector 48
114                                             sector 66
115                                             sector 66
116                                             sector 66
117                                             sector 65
118                                       sector-33 sohna
119                                              sector 4
120                                              sector 4
121                                       nirvana country
122                                             sector 48
123                                            sector 111
124                                            sector 111
125                                             sector 82
126                                  laxman vihar phase 2
127                                            sector 109
128                                             sector 73
129                                            sector 109
130                                              sector 9
131                                             sector 56
132                                             sector 48
133                                             sector 82
134                                            new colony
135                                              sector 7
136                                              sector 7
137                                              sector 7
138                                              sector 7
139                                       nirvana country
140                                             sector 48
141                                             sector 66
142                                            sector 109
143                                            sector 109
144                                            sector 109
145                                            sector 109
146                                            sector 109
147                                             sector 56
148                                            sector 17c
149                                            sector 109
150                                            sector 109
151                                            sector 70a
152                                            sector 70a
153                                           dlf phase 2
154                                            sector 109
155                                            sector 109
156                                         rajendra park
157                                  laxman vihar phase 2
158                                  laxman vihar phase 2
159                                  laxman vihar phase 2
160                                  laxman vihar phase 2
161                                  laxman vihar phase 2
162                                  laxman vihar phase 2
163                                   sushant lok phase 1
164                                            sector 109
165                                             sector 57
166                                             sector 55
167                                         shivaji nagar
168                                             sector 31
169                                   sushant lok phase 1
170                                   sushant lok phase 1
171                                       nirvana country
172                                       nirvana country
173                                           palam vihar
174                                            sector 109
175                                            sector 109
176                                            sector 70a
177                                            sector 109
200                                         dharam colony
201                                        krishna colony
202                                          laxman vihar
203                                           dlf phase 3
204                         ashok vihar phase 3 extension
205                                             sector 9a
206                                              sector 3
207                                            hira nagar
208                   gopal nagar, garhi ghasita, sonipat
209                    jat colony,fazilpur/taj nagar road
210                                          south city 1
211                                            sector 17a
212                                             sector 56
213                                                 kheri
214                                             madanpuri
215                                           dlf phase 3
216                                            sohna road
217                                       dayanand colony
218                                           mohan nagar
219                                         rajendra park
220                                            daulatabad
221                         ashok vihar phase 3 extension
222                                         vishnu garden
223                                           dlf phase 1
224                                             new basti
225                                         shivaji nagar
226                                               manesar
227                                            new colony
228                                              sector 8
229                                           ashok vihar
230                                           maruti kunj
231                                          laxmi garden
232                                           mohan nagar
233                                             sector 9b
234                                       saraswati vihar
235                                           imt manesar
236                                           bhora kalan
237                                    near nand hospital
238                                           dlf phase 1
239                                              shivpuri
240                                             sector 92
241                                             sector 76
242                                             sector 72
243                                            jyoti park
244                                                 sohna
245                                         subhash nagar
246                                       new palam vihar
247                                           palam vihar
248                                   surat nagar phase 2
249                                             sector 14
250                                             sector 33
251                                             sector 56
252                                           ashok vihar
253                                             sector 93
254                                              sector 5
255                                         rajendra park
256                                           rajiv nagar
257                                             madanpuri
258                               new palam vihar phase 1
259                                           arjun nagar
260                                   ashok vihar phase i
261                                              sector 5
262                                           surya vihar
263               block h ashok vihar phase iii extension
264                                           dlf phase 1
265                                        devilal colony
266                                             sector 38
267                                           surya vihar
268                                            prem nagar
269                                            bhim nagar
270                                  laxman vihar phase 2
271                                           surat nagar
272                                          gandhi nagar
273                                               khandsa
274                                            sector 109
275                         ashok vihar phase 3 extension
276                                            ravi nagar
277                                           maruti kunj
278                                         rajendra park
279                                             sector 50
280                                urban estate, sector 5
281                               new palam vihar phase 2
282                                      west rajiv nagar
283                         ashok vihar phase 3 extension
284                                   surat nagar phase 2
285                                             sector 11
286                                         vishnu garden
287                                   sushant lok phase 3
288                                     near khandsa road
289                                        devilal colony
290                                        sheetla colony
291                                          laxman vihar
292                                           farukhnagar
293                                            ravi nagar
294                                       mianwali colony
295                                              sector 8
296                                         dharam colony
297                                           palam vihar
298                                             sector 55
299                                       part 3 sector 5
300                                                 sohna
301                                             sector 38
302                                       saraswati vihar
303                                             sector 63
304                                               lucknow
305                                          pataudi road
306                                           surya vihar
307                                            ravi nagar
308                                             sector 81
309                                         subhash nagar
310                                             sector 38
311                                             sector 56
312                                       sector-33 sohna
313                                             sector 70
314                                            sector 105
315                                            jyoti park
316                                           dlf phase 2
317                                           malibu town
318                                             sector 28
319                                             sector 66
320                           c block sushant lok phase 1
321                                            bhim nagar
322                                            jyoti park
323                                       nirvana country
324                                             sector 12
325                                          laxman vihar
326                                          laxman vihar
327                                            sector 109
328                                            sector 109
329                                            sector 109
330                                            sector 109
331                                            sector 109
332                                          laxman vihar
333                                          laxman vihar
334                                          shakti nagar
335                                            sector 37d
336                                          baldev nagar
337                                              shivpuri
338                                             new basti
339                                             sector 56
340                                           rajiv nagar
341                                         vishnu garden
342                                          acharya puri
343                                               bhondsi
344                                            sector 105
345                                           arjun nagar
346                                           dlf phase 2
347                                             sector 92
348                                            sector 108
349                         ashok vihar phase 3 extension
350                         ashok vihar phase 3 extension
351                                            sector 109
352                                         garhi harsaru
353                                           arjun nagar
354                                 palam vihar extension
355                                           rajiv nagar
356                                           surya vihar
357                                          pratap nagar
358                                          baldev nagar
359                                       new palam vihar
360                                         subhash nagar
361                                              sector 1
362                      anand garden, sector-105 gurgaon
363                                            sector 10a
364                                             sector 13
365                                             sector 31
366                                               dhunela
367                                             sector 3a
368                                           heera nagar
369                                  laxman vihar phase 2
370                                         manohar nagar
371                                              sector 5
372                                                 sohna
373                                             sector 52
374                                          laxman vihar
375                                           arjun nagar
376                                             vir nagar
377                                             madanpuri
378                                            sector 82a

In [29]:
h.sample(5)

,property_name,link,society,price,area_persqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id,sector
606,1 Bedroom House for sale in Sector 3 Gurgaon,https://www.99acres.com/1-bhk-bedroom-independ...,nan,3.5,"9,210",(353 sq.m.) Built-up Area,Built Up area: 3800 (353.03 sq.m.),1,1,No,not avilable,"Gold Golf Links, Sector 3, Sohna, Gurgaon, Sec...",1,NaN,undefined,NaN,Looking for a 3 bhk independent floor for sale...,NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of...",Z67766806,sector 3
888,9 Bedroom House for sale in DLF Phase 4,https://www.99acres.com/9-bhk-bedroom-independ...,nan,11.25,"34,722",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),9,9,3+,"Pooja Room,Servant Room,Store Room","House No-, DLF Phase 4, Gurgaon, Haryana",2,North,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Huda city centr...",Do you wish to buy an independent house in dlf...,"['12 Wardrobe', '15 Fan', '1 Exhaust Fan', '12...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",L68674708,dlf phase 4
535,1 Bedroom House for sale in Sector 8 Gurgaon,https://www.99acres.com/1-bhk-bedroom-independ...,nan,0.45,"9,000",(46 sq.m.) Carpet Area,Carpet area: 500 (46.45 sq.m.),1,1,1,not avilable,"Sector 8, Sector 8 Gurgaon, Gurgaon, Haryana",3,East,undefined,NaN,1bhk residential house for resale in sector 8 ...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",I68022246,sector 8
417,2 Bedroom House for sale in Bhawani Enclave,https://www.99acres.com/2-bhk-bedroom-independ...,nan,1.1,"73,333",(14 sq.m.) Plot Area,Plot area 150(13.94 sq.m.),2,2,1,Others,"Bhawani Enclave, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['State bank ATM', 'Shri Multispeciality Hospi...","2 side open, 1 drawing room, 1 shop, 1 small r...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,NaN,L68891802,bhawani enclave
482,3 Bedroom House for sale in Baldev Nagar,https://www.99acres.com/3-bhk-bedroom-independ...,nan,0.45,"5,000",(84 sq.m.) Plot Area,Plot area 900(83.61 sq.m.),3,2,1,Others,"Baldev Nagar, Gurgaon, Haryana",2,North-West,10+ Year Old,"['Ankur Clinic and Maternity Home', 'Navjeevan...","100meter distance from main road, 25foot wide ...","['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Li...","['Feng Shui / Vaastu Compliant', 'Water Storage']","['Environment4 out of 5', 'Lifestyle4 out of 5...",Q68455832,baldev nagar

In [30]:
ind=h[h['balcony']=='No'].index
h.loc[ind,'balcony']=0

In [31]:
h['balcony'].value_counts()

balcony
3+    374
2     224
3     163
0     118
1     108
Name: count, dtype: int64

In [32]:
h['additionalRoom'].value_counts()

additionalRoom
not avilable                                     471
Servant Room                                      82
Pooja Room,Study Room,Servant Room,Store Room     63
Others                                            59
Pooja Room                                        38
Pooja Room,Study Room,Servant Room                34
Pooja Room,Study Room,Servant Room,Others         32
Store Room                                        31
Pooja Room,Servant Room                           24
Study Room,Servant Room                           19
Study Room                                        19
Servant Room,Store Room                           15
Pooja Room,Store Room                             11
Pooja Room,Study Room                             11
Pooja Room,Others                                 11
Pooja Room,Store Room,Study Room,Servant Room      9
Servant Room,Pooja Room                            8
Servant Room,Others                                8
Study Room,Servant Room,Pooja Room,Store Room      7
Pooja Room,Servant Room,Store Room                 7
Servant Room,Pooja Room,Store Room                 7
Store Room,Servant Room                            6
Pooja Room,Servant Room,Others                     5
Study Room,Pooja Room,Servant Room                 5
Servant Room,Store Room,Pooja Room                 5
Servant Room,Study Room,Pooja Room,Store Room      5
Servant Room,Study Room                            5
Store Room,Pooja Room                              4
Study Room,Servant Room,Store Room                 4
Pooja Room,Servant Room,Study Room,Store Room      4
Study Room,Servant Room,Store Room,Pooja Room      4
Pooja Room,Study Room,Others                       4
Study Room,Others                                  3
Study Room,Pooja Room,Servant Room,Store Room      3
Study Room,Servant Room,Pooja Room                 3
Pooja Room,Study Room,Store Room                   3
Study Room,Servant Room,Others                     2
Study Room,Pooja Room,Store Room,Servant Room      2
Study Room,Pooja Room                              2
Store Room,Pooja Room,Servant Room                 2
Study Room,Pooja Room,Store Room                   2
Pooja Room,Study Room,Store Room,Servant Room      2
Store Room,Pooja Room,Study Room                   2
Store Room,Pooja Room,Study Room,Servant Room      2
Servant Room,Study Room,Store Room,Pooja Room      2
Servant Room,Study Room,Pooja Room                 2
Study Room,Store Room                              1
Store Room,Pooja Room,Servant Room,Study Room      1
Servant Room,Store Room,Study Room,Pooja Room      1
Study Room,Store Room,Pooja Room                   1
Store Room,Servant Room,Study Room,Pooja Room      1
Pooja Room,Store Room,Servant Room                 1
Servant Room,Others,Pooja Room                     1
Study Room,Store Room,Servant Room,Pooja Room      1
Store Room,Study Room,Servant Room                 1
Store Room,Servant Room,Pooja Room                 1
Study Room,Others,Servant Room                     1
Name: count, dtype: int64

In [33]:
h.sample(5)

,property_name,link,society,price,area_persqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id,sector
697,5 Bedroom House for sale in DLF Phase 2,https://www.99acres.com/5-bhk-bedroom-independ...,dlf city plots phase 2,10.55,"39,074",(251 sq.m.) Plot Area,Plot area 300(250.84 sq.m.),5,6,3+,"Pooja Room,Study Room,Servant Room,Store Room","Kothi, DLF Phase 2, Gurgaon, Haryana",3,East,5 to 10 Year Old,"['Vodafone belvedere towers metro station', 'D...",East facing\nCorner\nBest deal available\nOld ...,"['4 Geyser', '5 Light', '1 Chimney', 'No AC', ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5...",H69802660,dlf phase 2
619,5 Bedroom House for sale in DLF Phase 1,https://www.99acres.com/5-bhk-bedroom-independ...,nan,4.5,"33,333",(125 sq.m.) Plot Area,Plot area 150(125.42 sq.m.),5,5,3+,not avilable,"DLF Phase 1, Gurgaon, Haryana",2,NaN,10+ Year Old,"['Guru dronacharya metro station', 'Dlf phase ...",Property is located in prime location of dlf 1...,NaN,['Water Storage'],"['Environment5 out of 5', 'Lifestyle5 out of 5...",V64373068,dlf phase 1
428,6 Bedroom House for sale in Sector 63A Gurgaon,https://www.99acres.com/6-bhk-bedroom-independ...,anant raj estates,8.5,"27,139",(291 sq.m.) Plot Area,Plot area 348(290.97 sq.m.),6,6,3+,"Pooja Room,Store Room","Sector 63A Gurgaon, Gurgaon, Haryana",3,East,Under Construction,"['Sector 55-56 Metro Station', 'Paras Trinity ...",It is a contemporary villa that is east-Facing...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5...",L60330100,sector 63a
738,2 Bedroom House for sale in Sector 10A Gurgaon,https://www.99acres.com/2-bhk-bedroom-independ...,nan,1.7,"18,888",(84 sq.m.) Plot Area,Plot area 900(83.61 sq.m.),2,1,2,Others,"Sector 10A Gurgaon, Gurgaon, Haryana",2,East,10+ Year Old,"['Rajiv Chowk Mosque', 'Gautam Hospital', 'Sai...","Beautifully located, park facing and east faci...","['3 Wardrobe', 'No AC', 'No Bed', 'No Chimney'...",['Park'],"['Environment4 out of 5', 'Lifestyle5 out of 5...",G69173270,sector 10a
711,4 Bedroom House for sale in Sector 17B Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,kothi,6.95,"15,444",(418 sq.m.) Plot Area,Plot area 500(418.06 sq.m.)Built Up area: 3500...,4,4,3+,"Pooja Room,Study Room,Servant Room,Store Room","Sector 17B Gurgaon, Gurgaon, Haryana",2,NaN,10+ Year Old,"['Iffco chowk metro station', 'Mg road metro s...",Excellent location near iffco chowk (Within wa...,NaN,"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment5 out of 5', 'Lifestyle5 out of 5...",W69409658,sector 17b

In [34]:
h.drop(columns=['property_name','link','address','property_id','rating'],inplace=True)

In [35]:
h.sample(5)

,society,price,area_persqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,sector
535,nan,0.45,"9,000",(46 sq.m.) Carpet Area,Carpet area: 500 (46.45 sq.m.),1,1,1,not avilable,3,East,undefined,NaN,1bhk residential house for resale in sector 8 ...,NaN,NaN,sector 8
153,nan,6.6,"36,667",(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),6,7,3+,"Study Room,Servant Room",2,East,5 to 10 Year Old,"['Mg road metro station', 'Sikandarpur metro s...","This 6 bhk house for sale in dlf phase 2, a we...","['9 Fan', '1 Exhaust Fan', '7 Geyser', '41 Lig...","['Feng Shui / Vaastu Compliant', 'Private Gard...",dlf phase 2
11,nan,9.0,"27,778",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),6,7,3+,"Study Room,Servant Room,Pooja Room,Store Room",3,North,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Huda city centr...",This is a old builtup property can be livable ...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...",dlf phase 4
734,nan,2.55,"13,178",(180 sq.m.) Built-up Area,Built Up area: 215 (179.77 sq.m.),3,3,2,not avilable,3,NaN,1 to 5 Year Old,"['Mg road metro station', 'Iffco chowk metro s...","Sushant lok phase 1, gurgaon, haryana ultra lu...","['5 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Centrally Ai...",a block sushant lok phase 1
496,nan,0.47,"8,012",(58 sq.m.) Plot Area,Plot area 624(57.97 sq.m.),2,1,1,Store Room,1,East,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Shre...",The property has a good front which has enough...,NaN,NaN,laxman vihar phase 2

In [36]:
h.isnull().sum()
# society-->nan in str

society              0
price               92
area_persqft        40
area                 0
areaWithType        73
bedRoom             73
bathroom            73
balcony             73
additionalRoom       0
noOfFloor           93
facing             386
agePossession       73
nearbyLocations    147
description         24
furnishDetails     317
features           386
sector               0
dtype: int64

In [37]:
def remove_comma(x):
    if type(x)==float:# for nan values
        return x
    else:
        l=x.split(',')
        return float(''.join(l))

In [38]:
h['area_persqft']=h['area_persqft'].apply(remove_comma)

In [39]:
h['area']

0               (242 sq.m.) Plot Area
1                (50 sq.m.) Plot Area
2                (51 sq.m.) Plot Area
3               (108 sq.m.) Plot Area
4                (52 sq.m.) Plot Area
5               (107 sq.m.) Plot Area
6               (301 sq.m.) Plot Area
7               (418 sq.m.) Plot Area
8               (264 sq.m.) Plot Area
9               (180 sq.m.) Plot Area
10              (125 sq.m.) Plot Area
11              (301 sq.m.) Plot Area
12              (136 sq.m.) Plot Area
13              (420 sq.m.) Plot Area
14              (251 sq.m.) Plot Area
15              (125 sq.m.) Plot Area
16              (334 sq.m.) Plot Area
17               (84 sq.m.) Plot Area
18              (201 sq.m.) Plot Area
19              (268 sq.m.) Plot Area
20              (244 sq.m.) Plot Area
21              (293 sq.m.) Plot Area
22              (301 sq.m.) Plot Area
23              (301 sq.m.) Plot Area
24              (180 sq.m.) Plot Area
25              (251 sq.m.) Plot Area
26              (471 sq.m.) Plot Area
27              (242 sq.m.) Plot Area
28              (220 sq.m.) Plot Area
29              (301 sq.m.) Plot Area
30              (210 sq.m.) Plot Area
31              (251 sq.m.) Plot Area
32              (293 sq.m.) Plot Area
33               (84 sq.m.) Plot Area
34              (134 sq.m.) Plot Area
35              (161 sq.m.) Plot Area
36              (251 sq.m.) Plot Area
37              (300 sq.m.) Plot Area
38              (251 sq.m.) Plot Area
39              (251 sq.m.) Plot Area
40              (167 sq.m.) Plot Area
41               (70 sq.m.) Plot Area
42              (251 sq.m.) Plot Area
43              (251 sq.m.) Plot Area
44              (255 sq.m.) Plot Area
45              (251 sq.m.) Plot Area
46              (167 sq.m.) Plot Area
47              (293 sq.m.) Plot Area
48              (242 sq.m.) Plot Area
49              (180 sq.m.) Plot Area
50              (145 sq.m.) Plot Area
51              (301 sq.m.) Plot Area
52              (418 sq.m.) Plot Area
53          (593 sq.m.) Built-up Area
54              (136 sq.m.) Plot Area
55              (241 sq.m.) Plot Area
56              (372 sq.m.) Plot Area
57              (135 sq.m.) Plot Area
58              (316 sq.m.) Plot Area
59              (316 sq.m.) Plot Area
73          (743 sq.m.) Built-up Area
74               (84 sq.m.) Plot Area
75      (467-681 sq.m.) Built-up Area
76      (384-392 sq.m.) Built-up Area
77            (232 sq.m.) Carpet Area
78              (180 sq.m.) Plot Area
79      (606-754 sq.m.) Built-up Area
80          (521 sq.m.) Built-up Area
81      (467-681 sq.m.) Built-up Area
82      (294-418 sq.m.) Built-up Area
83          (293 sq.m.) Built-up Area
84      (590-687 sq.m.) Built-up Area
85          (521 sq.m.) Built-up Area
86          (606 sq.m.) Built-up Area
87          (521 sq.m.) Built-up Area
88          (543 sq.m.) Built-up Area
89      (468-681 sq.m.) Built-up Area
90      (292-358 sq.m.) Built-up Area
91          (293 sq.m.) Built-up Area
92              (220 sq.m.) Plot Area
93              (286 sq.m.) Plot Area
94          (606 sq.m.) Built-up Area
95          (521 sq.m.) Built-up Area
96          (325 sq.m.) Built-up Area
97          (293 sq.m.) Built-up Area
98      (139-279 sq.m.) Built-up Area
99      (650-790 sq.m.) Built-up Area
100     (590-687 sq.m.) Built-up Area
101     (251-704 sq.m.) Built-up Area
102         (211 sq.m.) Built-up Area
103             (226 sq.m.) Plot Area
104             (502 sq.m.) Plot Area
105     (372-441 sq.m.) Built-up Area
106         (279 sq.m.) Built-up Area
107     (571-711 sq.m.) Built-up Area
108     (372-441 sq.m.) Built-up Area
109         (279 sq.m.) Built-up Area
110         (543 sq.m.) Built-up Area
111     (293-381 sq.m.) Built-up Area
112         (207 sq.m.) Built-up Area
113         (301 sq.m.) Built-up Area
114         (223 sq.m.) Built-up Area
115     (606-754 sq.m.) Built-up Area
116         (521 sq.m.) Built-up Area
117         (183 sq.m.) Built-up Area
118         (344 sq.m.) Built-up Area
119             (209 sq.m.) Plot Area
120             (460 sq.m.) Plot Area
121             (251 sq.m.) Plot Area
122             (815 sq.m.) Plot Area
123         (650 sq.m.) Built-up Area
124         (650 sq.m.) Built-up Area
125             (301 sq.m.) Plot Area
126              (73 sq.m.) Plot Area
127              (25 sq.m.) Plot Area
128         (543 sq.m.) Built-up Area
129             (502 sq.m.) Plot Area
130             (220 sq.m.) Plot Area
131             (254 sq.m.) Plot Area
132             (297 sq.m.) Plot Area
133             (301 sq.m.) Plot Area
134             (100 sq.m.) Plot Area
135             (244 sq.m.) Plot Area
136             (134 sq.m.) Plot Area
137             (209 sq.m.) Plot Area
138             (134 sq.m.) Plot Area
139             (223 sq.m.) Plot Area
140             (372 sq.m.) Plot Area
141             (209 sq.m.) Plot Area
142             (418 sq.m.) Plot Area
143             (502 sq.m.) Plot Area
144             (334 sq.m.) Plot Area
145             (502 sq.m.) Plot Area
146             (226 sq.m.) Plot Area
147             (135 sq.m.) Plot Area
148             (161 sq.m.) Plot Area
149             (226 sq.m.) Plot Area
150             (206 sq.m.) Plot Area
151             (557 sq.m.) Plot Area
152         (557 sq.m.) Built-up Area
153             (167 sq.m.) Plot Area
154         (650 sq.m.) Built-up Area
155             (743 sq.m.) Plot Area
156              (67 sq.m.) Plot Area
157             (125 sq.m.) Plot Area
158            (1254 sq.m.) Plot Area
159               (6 sq.m.) Plot Area
160               (7 sq.m.) Plot Area
161               (6 sq.m.) Plot Area
162               (7 sq.m.) Plot Area
163             (180 sq.m.) Plot Area
164             (226 sq.m.) Plot Area
165            (2592 sq.m.) Plot Area
166             (140 sq.m.) Plot Area
167             (167 sq.m.) Plot Area
168             (145 sq.m.) Plot Area
169              (89 sq.m.) Plot Area
170             (180 sq.m.) Plot Area
171             (418 sq.m.) Plot Area
172             (201 sq.m.) Plot Area
173             (360 sq.m.) Plot Area
174             (418 sq.m.) Plot Area
175             (418 sq.m.) Plot Area
176         (511 sq.m.) Built-up Area
177             (502 sq.m.) Plot Area
200              (13 sq.m.) Plot Area
201              (51 sq.m.) Plot Area
202              (64 sq.m.) Plot Area
203              (50 sq.m.) Plot Area
204              (99 sq.m.) Plot Area
205             (293 sq.m.) Plot Area
206          (94 sq.m.) Built-up Area
207              (52 sq.m.) Plot Area
208              (84 sq.m.) Plot Area
209              (98 sq.m.) Plot Area
210             (230 sq.m.) Plot Area
211             (151 sq.m.) Plot Area
212             (140 sq.m.) Plot Area
213               (5 sq.m.) Plot Area
214              (84 sq.m.) Plot Area
215         (279 sq.m.) Built-up Area
216              (63 sq.m.) Plot Area
217              (56 sq.m.) Plot Area
218              (84 sq.m.) Plot Area
219          (42 sq.m.) Built-up Area
220               (7 sq.m.) Plot Area
221              (42 sq.m.) Plot Area
222            (46 sq.m.) Carpet Area
223              (91 sq.m.) Plot Area
224              (22 sq.m.) Plot Area
225             (167 sq.m.) Plot Area
226             (166 sq.m.) Plot Area
227             (334 sq.m.) Plot Area
228              (84 sq.m.) Plot Area
229          (10 sq.m.) Built-up Area
230             (158 sq.m.) Plot Area
231         (121 sq.m.) Built-up Area
232             (139 sq.m.) Plot Area
233          (42 sq.m.) Built-up Area
234             (125 sq.m.) Plot Area
235             (111 sq.m.) Plot Area
236              (63 sq.m.) Plot Area
237              (84 sq.m.) Plot Area
238             (167 sq.m.) Plot Area
239             (209 sq.m.) Plot Area
240             (261 sq.m.) Plot Area
241           (260 sq.m.) Carpet Area
242             (339 sq.m.) Plot Area
243            (92 sq.m.) Carpet Area
244         (104 sq.m.) Built-up Area
245          (63 sq.m.) Built-up Area
246              (25 sq.m.) Plot Area
247           (302 sq.m.) Carpet Area
248              (43 sq.m.) Plot Area
249             (209 sq.m.) Plot Area
250             (418 sq.m.) Plot Area
251             (253 sq.m.) Plot Area
252             (135 sq.m.) Plot Area
253             (107 sq.m.) Plot Area
254         (316 sq.m.) Built-up Area
255              (33 sq.m.) Plot Area
256           (301 sq.m.) Carpet Area
257             (125 sq.m.) Plot Area
258              (84 sq.m.) Plot Area
259              (33 sq.m.) Plot Area
260            (2415 sq.m.) Plot Area
261              (84 sq.m.) Plot Area
262             (125 sq.m.) Plot Area
263              (88 sq.m.) Plot Area
264             (166 sq.m.) Plot Area
265          (76 sq.m.) Built-up Area
266          (32 sq.m.) Built-up Area
267            (50 sq.m.) Carpet Area
268          (18 sq.m.) Built-up Area
269          (22 sq.m.) Built-up Area
270             (431 sq.m.) Plot Area
271             (121 sq.m.) Plot Area
272           (5 sq.m.) Built-up Area
273              (41 sq.m.) Plot Area
274         (200 sq.m.) Built-up Area
275          (93 sq.m.) Built-up Area
276          (42 sq.m.) Built-up Area
277              (52 sq.m.) Plot Area
278              (84 sq.m.) Plot Area
279         (279 sq.m.) Built-up Area
280             (171 sq.m.) Plot Area
281             (372 sq.m.) Plot Area
282             (301 sq.m.) Plot Area
283          (12 sq.m.) Built-up Area
284               (5 sq.m.) Plot Area
285             (251 sq.m.) Plot Area
286         (325 sq.m.) Built-up Area
287             (201 sq.m.) Plot Area
288              (67 sq.m.) Plot Area
289            (28 sq.m.) Carpet Area
290          (20 sq.m.) Built-up Area
291          (44 sq.m.) Built-up Area
292              (84 sq.m.) Plot Area
293             (133 sq.m.) Plot Area
294           (167 sq.m.) Carpet Area
295          (74 sq.m.) Built-up Area
296            (93 sq.m.) Carpet Area
297         (278 sq.m.) Built-up Area
298         (139 sq.m.) Built-up Area
299             (153 sq.m.) Plot Area
300              (28 sq.m.) Plot Area
301           (134 sq.m.) Carpet Area
302           (121 sq.m.) Carpet Area
303         (367 sq.m.) Built-up Area
304             (209 sq.m.) Plot Area
305          (809371 sq.m.) Plot Area
306              (90 sq.m.) Plot Area
307              (19 sq.m.) Plot Area
308     (509-543 sq.m.) Built-up Area
309             (167 sq.m.) Plot Area
310             (160 sq.m.) Plot Area
311             (135 sq.m.) Plot Area
312         (344 sq.m.) Built-up Area
313         (697 sq.m.) Built-up Area
314         (111 sq.m.) Built-up Area
315              (92 sq.m.) Plot Area
316         (557 sq.m.) Built-up Area
317         (149 sq.m.) Built-up Area
318             (465 sq.m.) Plot Area
319         (353 sq.m.) Built-up Area
320             (326 sq.m.) Plot Area
321               (6 sq.m.) Plot Area
322          (31 sq.m.) Built-up Area
323         (452 sq.m.) Built-up Area
324             (385 sq.m.) Plot Area
325         (167 sq.m.) Built-up Area
326         (223 sq.m.) Built-up Area
327         (540 sq.m.) Built-up Area
328         (363 sq.m.) Built-up Area
329     (468-681 sq.m.) Built-up Area
330     (292-358 sq.m.) Built-up Area
331         (293 sq.m.) Built-up Area
332              (33 sq.m.) Plot Area
333          (92 sq.m.) Built-up Area
334              (93 sq.m.) Plot Area
335             (177 sq.m.) Plot Area
336          (84 sq.m.) Built-up Area
337             (167 sq.m.) Plot Area
338          (74 sq.m.) Built-up Area
339              (34 sq.m.) Plot Area
340          (87 sq.m.) Built-up Area
341              (42 sq.m.) Plot Area
342         (144 sq.m.) Built-up Area
343             (325 sq.m.) Plot Area
344           (9 sq.m.) Built-up Area
345          (51 sq.m.) Built-up Area
346           (929 sq.m.) Carpet Area
347         (219 sq.m.) Built-up Area
348         (279 sq.m.) Built-up Area
349         (102 sq.m.) Built-up Area
350         (279 sq.m.) Built-up Area
351         (219 sq.m.) Built-up Area
352          (13 sq.m.) Built-up Area
353              (33 sq.m.) Plot Area
354            (49 sq.m.) Carpet Area
355           (7 sq.m.) Built-up Area
356         (372 sq.m.) Built-up Area
357         (233 sq.m.) Built-up Area
358          (59 sq.m.) Built-up Area
359              (84 sq.m.) Plot Area
360            (84 sq.m.) Carpet Area
361         (204 sq.m.) Built-up Area
362             (209 sq.m.) Plot Area
363             (308 sq.m.) Plot Area
364              (83 sq.m.) Plot Area
365             (220 sq.m.) Plot Area
366         (112 sq.m.) Built-up Area
367             (232 sq.m.) Plot Area
368              (84 sq.m.) Plot Area
369              (41 sq.m.) Plot Area
370             (418 sq.m.) Plot Area
371          (93 sq.m.) Built-up Area
372             (167 sq.m.) Plot Area
373         (201 sq.m.) Built-up Area
374              (54 sq.m.) Plot Area
375              (52 sq.m.) Plot Area
376            (75 sq.m.) Carpet Area
377              (42 sq.m.) Plot Area
378         (478 sq.m.) Built-up Area
379              (57 sq.m.) Plot Area
380              (34 sq.m.) Plot Area
381              (89 sq.m.) Plot Area
382             (132 sq.m.) Plot Area
383              (71 sq.m.) Plot Area
384             (100 sq.m.) Plot Area
385         (100 sq.m.) Built-up Area
386         (105 sq.m.) Built-up Area
387              (95 sq.m.) Plot Area
388            (84 sq.m.) Carpet Area
389              (51 sq.m.) Plot Area
390              (84 sq.m.) Plot Area
391         (158 sq.m.) Built-up Area
392         (340 sq.m.) Built-up Area
393             (232 sq.m.) Plot Area
394             (134 sq.m.) Plot Area
395         (650 sq.m.) Built-up Area
396             (226 sq.m.) Plot Area
397             (115 sq.m.) Plot Area
398             (146 sq.m.) Plot Area
399             (109 sq.m.) Plot Area
400              (24 sq.m.) Plot Area
401          (56 sq.m.) Built-up Area
402         (585 sq.m.) Built-up Area
403              (84 sq.m.) Plot Area
404             (167 sq.m.) Plot Area
405          (45 sq.m.) Built-up Area
406          (15 sq.m.) Built-up Area
407         (220 sq.m.) Built-up Area
408          (45 sq.m.) Built-up Area
409          (25 sq.m.) Built-up Area
410               (9 sq.m.) Plot Area
411            (56 sq.m.) Carpet Area
412         (102 sq.m.) Built-up Area
413               (5 sq.m.) Plot Area
414              (50 sq.m.) Plot Area
415          (33 sq.m.) Built-up Area
416              (84 sq.m.) Plot Area
417              (14 sq.m.) Plot Area
418         (681 sq.m.) Built-up Area
419           (251 sq.m.) Carpet Area
420             (301 sq.m.) Plot Area
421             (151 sq.m.) Plot Area
422              (33 sq.m.) Plot Area
423              (18 sq.m.) Plot Area
424            (75 sq.m.) Carpet Area
425              (93 sq.m.) Plot Area
426           (325 sq.m.) Carpet Area
427            (23 sq.m.) Carpet Area
428             (291 sq.m.) Plot Area
429              (84 sq.m.) Plot Area
430              (84 sq.m.) Plot Area
431            (40 sq.m.) Carpet Area
432             (226 sq.m.) Plot Area
433             (246 sq.m.) Plot Area
434             (435 sq.m.) Plot Area
435              (52 sq.m.) Plot Area
436             (460 sq.m.) Plot Area
437              (47 sq.m.) Plot Area
438              (50 sq.m.) Plot Area
439               (5 sq.m.) Plot Area
440              (85 sq.m.) Plot Area
441            (7692 sq.m.) Plot Area
442             (226 sq.m.) Plot Area
443              (33 sq.m.) Plot Area
444             (124 sq.m.) Plot Area
445              (84 sq.m.) Plot Area
446         (132 sq.m.) Built-up Area
447            (93 sq.m.) Carpet Area
448         (301 sq.m.) Built-up Area
449              (73 sq.m.) Plot Area
450              (59 sq.m.) Plot Area
451             (105 sq.m.) Plot Area
452               (7 sq.m.) Plot Area
453         (163 sq.m.) Built-up Area
454             (184 sq.m.) Plot Area
455         (105 sq.m.) Built-up Area
456              (52 sq.m.) Plot Area
457             (293 sq.m.) Plot Area
458              (49 sq.m.) Plot Area
459              (84 sq.m.) Plot Area
460             (113 sq.m.) Plot Area
461         (132 sq.m.) Built-up Area
462              (84 sq.m.) Plot Area
463            (84 sq.m.) Carpet Area
464             (167 sq.m.) Plot Area
465             (136 sq.m.) Plot Area
466              (33 sq.m.) Plot Area
467             (109 sq.m.) Plot Area
468            (40 sq.m.) Carpet Area
469         (483 sq.m.) Built-up Area
470              (42 sq.m.) Plot Area
471              (46 sq.m.) Plot Area
472              (50 sq.m.) Plot Area
473           (20064 sq.m.) Plot Area
474              (56 sq.m.) Plot Area
475          (15 sq.m.) Built-up Area
476              (14 sq.m.) Plot Area
477              (98 sq.m.) Plot Area
478         (328 sq.m.) Built-up Area
479             (336 sq.m.) Plot Area
480               (5 sq.m.) Plot Area
481             (167 sq.m.) Plot Area
482              (84 sq.m.) Plot Area
483             (560 sq.m.) Plot Area
484             (110 sq.m.) Plot Area
485             (167 sq.m.) Plot Area
486           (151 sq.m.) Carpet Area
487              (56 sq.m.) Plot Area
488              (76 sq.m.) Plot Area
489              (15 sq.m.) Plot Area
490              (40 sq.m.) Plot Area
491            (1115 sq.m.) Plot Area
492           (234 sq.m.) Carpet Area
493              (43 sq.m.) Plot Area
494              (42 sq.m.) Plot Area
495          (42 sq.m.) Built-up Area
496              (58 sq.m.) Plot Area
497              (28 sq.m.) Plot Area
498              (56 sq.m.) Plot Area
499              (65 sq.m.) Plot Area
500              (42 sq.m.) Plot Area
501             (372 sq.m.) Plot Area
502              (33 sq.m.) Plot Area
503             (125 sq.m.) Plot Area
504             (121 sq.m.) Plot Area
505             (117 sq.m.) Plot Area
506             (125 sq.m.) Plot Area
507              (84 sq.m.) Plot Area
508             (100 sq.m.) Plot Area
509              (42 sq.m.) Plot Area
510              (50 sq.m.) Plot Area
511              (42 sq.m.) Plot Area
512             (113 sq.m.) Plot Area
513             (390 sq.m.) Plot Area
514             (167 sq.m.) Plot Area
515              (63 sq.m.) Plot Area
516              (84 sq.m.) Plot Area
517             (136 sq.m.) Plot Area
518              (74 sq.m.) Plot Area
519              (99 sq.m.) Plot Area
520              (42 sq.m.) Plot Area
521             (174 sq.m.) Plot Area
522          (6062 sq.m.) Carpet Area
523            (49 sq.m.) Carpet Area
524           (5 sq.m.) Built-up Area
525          (89 sq.m.) Built-up Area
526          (89 sq.m.) Built-up Area
527              (50 sq.m.) Plot Area
528              (42 sq.m.) Plot Area
529              (98 sq.m.) Plot Area
530          (52 sq.m.) Built-up Area
531         (188 sq.m.) Built-up Area
532             (5 sq.m.) Carpet Area
533           (301 sq.m.) Carpet Area
534         (117 sq.m.) Built-up Area
535            (46 sq.m.) Carpet Area
536         (251 sq.m.) Built-up Area
537         (149 sq.m.) Built-up Area
538         (139 sq.m.) Built-up Area
539         (125 sq.m.) Built-up Area
540            (84 sq.m.) Carpet Area
541          (98 sq.m.) Built-up Area
542         (251 sq.m.) Built-up Area
543         (135 sq.m.) Built-up Area
544         (418 sq.m.) Built-up Area
545         (301 sq.m.) Built-up Area
546         (242 sq.m.) Built-up Area
547           (291 sq.m.) Carpet Area
548         (207 sq.m.) Built-up Area
549         (124 sq.m.) Built-up Area
550         (167 sq.m.) Built-up Area
551             (204 sq.m.) Plot Area
552           (195 sq.m.) Carpet Area
553         (681 sq.m.) Built-up Area
554              (84 sq.m.) Plot Area
555              (51 sq.m.) Plot Area
556               (9 sq.m.) Plot Area
557             (161 sq.m.) Plot Area
558              (84 sq.m.) Plot Area
559              (33 sq.m.) Plot Area
560          (33 sq.m.) Built-up Area

In [41]:
h.to_csv('house_cleaned.csv',index=False)

In [ ]:
{}